<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionEmpresaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Empresa.SP_MANTENIMIENTO_COMPRAS_SUPLIDORES" Method="SP_MANTENIMIENTO_COMPRAS_SUPLIDORES">
    <Parameter Name="IdCompraSuplidor" Parameter="idCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdSuplidor" Parameter="idSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNCCedula" Parameter="rNCCedula" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoBienesServicios" Parameter="idTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NCF" Parameter="nCF" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NCFModificado" Parameter="nCFModificado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaComprobante" Parameter="fechaComprobante" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaPago" Parameter="fechaPago" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MontoFacturadoServicios" Parameter="montoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoFacturadoBienes" Parameter="montoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalMontoFacturado" Parameter="totalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISFacturado" Parameter="iTBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISRetenido" Parameter="iTBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISSujetoProporcionalidad" Parameter="iTBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISLlevadoCosto" Parameter="iTBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPorAdelantar" Parameter="iTBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPercibidoCompras" Parameter="iTBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoRetencionISR" Parameter="idTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoRetencionRenta" Parameter="montoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ISRPercibidoCompras" Parameter="iSRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoSelectivoConsumo" Parameter="impuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OtrosImpuestosTasa" Parameter="otrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPropinaLegal" Parameter="montoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdFormaPago" Parameter="idFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCreado" Parameter="fechaCreado" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_COMPRAS_SUPLIDORESResult">
      <Column Name="IdCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="RNCCedula" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NCFModificado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaComprobante" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MontoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="MontoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ISRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_REGISTROS_COMPRA_SUPLIDORES" Method="SP_BUSCA_REGISTROS_COMPRA_SUPLIDORES">
    <Parameter Name="IdCompraSuplidor" Parameter="idCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdSuplidor" Parameter="idSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNCCedula" Parameter="rNCCedula" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaCreadoDesde" Parameter="fechaCreadoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCreadoHasta" Parameter="fechaCreadoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_REGISTROS_COMPRA_SUPLIDORESResult">
      <Column Name="IdCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoSuplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Suplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNCCedula" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoBienesServicios" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoBienesServicio" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NCFModificado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaComprobante0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaComprobante" Type="System.String" DbType="VarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="FechaPago0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.String" DbType="VarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="MontoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoRetencionISR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoRetencionISR" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="MontoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ISRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FormaPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaCreado0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_DEPARTAMENTOS" Method="SP_MANTENIMIENTO_DEPARTAMENTOS">
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_DEPARTAMENTOSResult">
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_DEPARTAMENTOS" Method="SP_BUSCA_DEPARTAMENTOS">
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_DEPARTAMENTOSResult">
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CARGOS" Method="SP_BUSCA_CARGOS">
    <Parameter Name="IdCargo" Parameter="idCargo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CARGOSResult">
      <Column Name="IdCargo" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_CARGOS" Method="SP_MANTENIMIENTO_CARGOS">
    <Parameter Name="IdCargo" Parameter="idCargo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CARGOSResult">
      <Column Name="IdCargo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_TIPO_EMPLEADO" Method="SP_BUSCA_TIPO_EMPLEADO">
    <Parameter Name="IdTipoEmpleado" Parameter="idTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_EMPLEADOResult">
      <Column Name="IdTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="TipoEmpleado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_TIPO_EMPLEADO" Method="SP_MANTENIMIENTO_TIPO_EMPLEADO">
    <Parameter Name="IdTipoEmpleado" Parameter="idTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Idusuario" Parameter="idusuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_EMPLEADOResult">
      <Column Name="IdTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_TIPO_NOMINA" Method="SP_BUSCA_TIPO_NOMINA">
    <Parameter Name="IdTipoNomina" Parameter="idTipoNomina" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_NOMINAResult">
      <Column Name="IdTipoNomina" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="TipoNomina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuairoModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_TIPO_NOMINA" Method="SP_MANTENIMIENTO_TIPO_NOMINA">
    <Parameter Name="IdTipoNomina" Parameter="idTipoNomina" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_NOMINAResult">
      <Column Name="IdTipoNomina" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuairoModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_LISTADO_BANCOS" Method="SP_BUSCA_LISTADO_BANCOS">
    <Parameter Name="IdBanco" Parameter="idBanco" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Banco" Parameter="banco" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroReistros" Parameter="numeroReistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_LISTADO_BANCOSResult">
      <Column Name="IdBanco" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="CuentaContable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Banco" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_DE_BANCOS" Method="SP_MANTENIMIENTO_DE_BANCOS">
    <Parameter Name="IdBanco" Parameter="idBanco" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CuentaContable" Parameter="cuentaContable" Type="System.Int32" DbType="Int" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(2,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_DE_BANCOSResult">
      <Column Name="IdBanco" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CuentaContable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_TIPO_MOVIMIENTO" Method="SP_BUSCA_TIPO_MOVIMIENTO">
    <Parameter Name="IdTipoMovimiento" Parameter="idTipoMovimiento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_MOVIMIENTOResult">
      <Column Name="IdTipoMovimiento" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="TipoMovimiento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_TIPO_MOVIMIENTO" Method="SP_MANTENIMIENTO_TIPO_MOVIMIENTO">
    <Parameter Name="IdTipoMovimiento" Parameter="idTipoMovimiento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_MOVIMIENTOResult">
      <Column Name="IdTipoMovimiento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_RETENCIONES" Method="SP_BUSCA_RETENCIONES">
    <Parameter Name="IdRetencion" Parameter="idRetencion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_RETENCIONESResult">
      <Column Name="IdRetencion" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Retencion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_RETENCIONES" Method="SP_MANTENIMIENTO_RETENCIONES">
    <Parameter Name="IdRetencion" Parameter="idRetencion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_RETENCIONESResult">
      <Column Name="IdRetencion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_PORCIENTO_RETENCIONES" Method="SP_MANTENIMIENTO_PORCIENTO_RETENCIONES">
    <Parameter Name="IdPorcientoRetencion" Parameter="idPorcientoRetencion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdRetencion" Parameter="idRetencion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="MontoInicial" Parameter="montoInicial" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoFinal" Parameter="montoFinal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoSumar" Parameter="montoSumar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoCia" Parameter="porcientoCia" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoEmpleado" Parameter="porcientoEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_PORCIENTO_RETENCIONESResult">
      <Column Name="IdPorcientoRetencion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdRetencion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoInicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFinal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoSumar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoCia" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_PORCIENTO_RETENCIONES" Method="SP_BUSCA_PORCIENTO_RETENCIONES">
    <Parameter Name="IdPorcientoRetencion" Parameter="idPorcientoRetencion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdRetencion" Parameter="idRetencion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_PORCIENTO_RETENCIONESResult">
      <Column Name="IdPorcientoRetencion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdRetencion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Retencion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoInicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFinal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoSumar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoCia" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_NACIONALIDAD" Method="SP_BUSCA_NACIONALIDAD">
    <Parameter Name="IdNacionalidad" Parameter="idNacionalidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_NACIONALIDADResult">
      <Column Name="IdNacionalidad" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nacionalidad" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_NACIONALIDAD" Method="SP_MANTENIMIENTO_NACIONALIDAD">
    <Parameter Name="IdNacionalidad" Parameter="idNacionalidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_NACIONALIDADResult">
      <Column Name="IdNacionalidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_ESTADO_CIVIL" Method="SP_MANTENIMIENTO_ESTADO_CIVIL">
    <Parameter Name="IdEstadoCivil" Parameter="idEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_ESTADO_CIVILResult">
      <Column Name="IdEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_FORMA_PAGO_EMPLEADO" Method="SP_MANTENIMIENTO_FORMA_PAGO_EMPLEADO">
    <Parameter Name="IdFormaPagoEmpleado" Parameter="idFormaPagoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_FORMA_PAGO_EMPLEADOResult">
      <Column Name="IdFormaPagoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_ESTADO_CIVIL" Method="SP_BUSCA_ESTADO_CIVIL">
    <Parameter Name="IdEstadoCivil" Parameter="idEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_ESTADO_CIVILResult">
      <Column Name="IdEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="EstadoCivil" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_FORMA_PAGO_EMPLEADO" Method="SP_BUSCA_FORMA_PAGO_EMPLEADO">
    <Parameter Name="IdFormaPago" Parameter="idFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_FORMA_PAGO_EMPLEADOResult">
      <Column Name="IdFormaPagoEmpleado" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="FormaPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_EMPLEADOS" Method="SP_MANTENIMIENTO_EMPLEADOS">
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdNacionalidad" Parameter="idNacionalidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdTipoEmpleado" Parameter="idTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTioNomina" Parameter="idTioNomina" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCargo" Parameter="idCargo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Telefono1" Parameter="telefono1" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Telefono2" Parameter="telefono2" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdEstadoCivil" Parameter="idEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Sueldo" Parameter="sueldo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OtrosIngresos" Parameter="otrosIngresos" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdFormaPago" Parameter="idFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaIngreso" Parameter="fechaIngreso" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaNacimiento" Parameter="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AplicaParaComision" Parameter="aplicaParaComision" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorcientoCOmisionVentas" Parameter="porcientoCOmisionVentas" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoComsiionServicio" Parameter="porcientoComsiionServicio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_EMPLEADOSResult">
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdNacionalidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NSS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTioNomina" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCargo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Telefono1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telefono2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sueldo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosIngresos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AplicaParaComision" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorcientoCOmisionVentas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoComsiionServicio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_EMPLEADO" Method="SP_BUSCA_EMPLEADO">
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombreEmpleado" Parameter="nombreEmpleado" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaIngresoDesde" Parameter="fechaIngresoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaIngresoHasta" Parameter="fechaIngresoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_EMPLEADOResult">
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreEmpleado" Type="System.String" DbType="VarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdNacionalidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nacionalidad" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NSS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdTipoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoEmpleado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTioNomina" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoNomina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCargo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telefono2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstadoCivil" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="EstadoCivil" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sueldo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosIngresos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FormaPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaIngreso0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaIngreso" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaNacimiento0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="AplicaParaComision0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AplicaParaComision" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PorcientoCOmisionVentas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoComsiionServicio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadActivos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadInactivos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_DATOS_EMPLEADOS_COMISION" Method="SP_BUSCA_DATOS_EMPLEADOS_COMISION">
    <Parameter Name="NombreEmpleado" Parameter="nombreEmpleado" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="SP_BUSCA_DATOS_EMPLEADOS_COMISIONResult">
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="PorcientoCOmisionVentas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoComsiionServicio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CITAS_DETALLE" Method="SP_BUSCA_CITAS_DETALLE">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_CITAS_DETALLEResult">
      <Column Name="NumeroConectorCita" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_GUARDAR_DATOS_CITAS_DETALLE" Method="SP_GUARDAR_DATOS_CITAS_DETALLE">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Precion" Parameter="precion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="DescripcionProducto" Parameter="descripcionProducto" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_CITAS_DETALLEResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_PROCESAR_INFORMACION_Encabezado_CITAS" Method="SP_PROCESAR_INFORMACION_Encabezado_CITAS">
    <Parameter Name="IdCitas" Parameter="idCitas" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCita" Parameter="fechaCita" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Hora" Parameter="hora" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroConectorCita" Parameter="numeroConectorCita" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_Encabezado_CITASResult">
      <Column Name="IdCitas" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCita" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConectorCita" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CITAS_ENCABEZADO" Method="SP_BUSCA_CITAS_ENCABEZADO">
    <Parameter Name="IdCIta" Parameter="idCIta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCitaDesde" Parameter="fechaCitaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCitaHasta" Parameter="fechaCitaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumeropAGINA" Parameter="numeropAGINA" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CITAS_ENCABEZADOResult">
      <Column Name="IdCitas" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Empleado" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="FechaCita0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCita" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConectorCita" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CLIENTES" Method="SP_BUSCA_CLIENTES">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnvioEmail" Parameter="envioEmail" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CLIENTESResult">
      <Column Name="IdCliente" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaNacimiento0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="AlertaCumpleanos0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AlertaCumpleanos" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="EnvioEmail0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnvioEmail" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="MontoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadClientes" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_CLIENTES" Method="SP_MANTENIMIENTO_CLIENTES">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaNacimiento" Parameter="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="AlertaCumpleanos" Parameter="alertaCumpleanos" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoCredito" Parameter="montoCredito" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EnvioEmail" Parameter="envioEmail" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CLIENTESResult">
      <Column Name="IdCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AlertaCumpleanos" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MontoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EnvioEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MOSTRAR_CUMPLEANOS_CLIENTES" Method="SP_MOSTRAR_CUMPLEANOS_CLIENTES">
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MOSTRAR_CUMPLEANOS_CLIENTESResult">
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Edad" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="MesNacimiento" Type="System.String" DbType="VarChar(44) NOT NULL" CanBeNull="false" />
      <Column Name="MesActual" Type="System.String" DbType="VarChar(44) NOT NULL" CanBeNull="false" />
      <Column Name="Cumpleanos" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CORREOS_CLIENTES" Method="SP_BUSCA_CORREOS_CLIENTES">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_CORREOS_CLIENTESResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_PROCESAR_INFORMACION_LISTADO_CORREO_ENVIAR" Method="SP_PROCESAR_INFORMACION_LISTADO_CORREO_ENVIAR">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_LISTADO_CORREO_ENVIARResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>