<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionCajaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.26.24.199;Initial Catalog=DSMarket;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="Caja.SP_ESTATUS_CAJA" Method="SP_ESTATUS_CAJA">
    <ElementType Name="SP_ESTATUS_CAJAResult">
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Caja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_AFECTAR_CAJA_GENERAL" Method="SP_AFECTAR_CAJA_GENERAL">
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoActual" Parameter="montoActual" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_AFECTAR_CAJA_GENERALResult">
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_GUARDAR_HISTORIAL_CAJA" Method="SP_GUARDAR_HISTORIAL_CAJA">
    <Parameter Name="IdHistorialCaja" Parameter="idHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_HISTORIAL_CAJAResult">
      <Column Name="IdHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_BUSCA_HISTORIAL_CAJA" Method="SP_BUSCA_HISTORIAL_CAJA">
    <Parameter Name="IdHistorialCaja" Parameter="idHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BUSCA_HISTORIAL_CAJAResult">
      <Column Name="IdHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>