#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMarket.Data.Conexion.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSMarket")]
	public partial class BDConexionHistorialDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionHistorialDataContext() : 
				base(global::DSMarket.Data.Properties.Settings.Default.DSMarketConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionHistorialDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionHistorialDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionHistorialDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionHistorialDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_PROCESAR_INFORMACION_GANANCIA_VENTA")]
		public ISingleResult<SP_PROCESAR_INFORMACION_GANANCIA_VENTAResult> SP_PROCESAR_INFORMACION_GANANCIA_VENTA(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstatusFacturacion", DbType="Decimal(20,0)")] System.Nullable<decimal> idEstatusFacturacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="VarChar(100)")] string estatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Decimal(20,0)")] System.Nullable<decimal> idCategoria, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoProducto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioCompra", DbType="Decimal(20,2)")] System.Nullable<decimal> precioCompra, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioVenta", DbType="Decimal(20,2)")] System.Nullable<decimal> precioVenta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadVendida", DbType="Decimal(20,0)")] System.Nullable<decimal> cantidadVendida, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescuentoAplicado", DbType="Decimal(20,2)")] System.Nullable<decimal> descuentoAplicado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalDescuentoAplicado", DbType="Decimal(20,2)")] System.Nullable<decimal> totalDescuentoAplicado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalVenta", DbType="Decimal(20,2)")] System.Nullable<decimal> totalVenta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalPrecioCompra", DbType="Decimal(20,2)")] System.Nullable<decimal> totalPrecioCompra, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ganancia", DbType="Decimal(20,2)")] System.Nullable<decimal> ganancia, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idEstatusFacturacion, estatus, numeroFactura, descripcion, idCategoria, idTipoProducto, precioCompra, precioVenta, cantidadVendida, descuentoAplicado, totalDescuentoAplicado, totalVenta, totalPrecioCompra, ganancia, accion);
			return ((ISingleResult<SP_PROCESAR_INFORMACION_GANANCIA_VENTAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_PROCESAR_INFORMACION_INFORMACION_VENTAS")]
		public ISingleResult<SP_PROCESAR_INFORMACION_INFORMACION_VENTASResult> SP_PROCESAR_INFORMACION_INFORMACION_VENTAS(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFActura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFActura, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoFacturacion", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoFacturacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="VarChar(30)")] string numeroConector, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FacturadoA", DbType="VarChar(100)")] string facturadoA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCF", DbType="VarChar(30)")] string nCF, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFActuracion", DbType="Date")] System.Nullable<System.DateTime> fechaFActuracion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalProductos", DbType="Int")] System.Nullable<int> totalProductos, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalServicios", DbType="Int")] System.Nullable<int> totalServicios, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalItems", DbType="Int")] System.Nullable<int> totalItems, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubTotal", DbType="Decimal(20,2)")] System.Nullable<decimal> subTotal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="Decimal(20,2)")] System.Nullable<decimal> descuento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Impuesto", DbType="Decimal(20,2)")] System.Nullable<decimal> impuesto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Decimal(20,2)")] System.Nullable<decimal> total, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPago", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoPago, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoPagado", DbType="Decimal(20,0)")] System.Nullable<decimal> montoPagado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cambio", DbType="Decimal(20,0)")] System.Nullable<decimal> cambio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMoneda", DbType="Decimal(20,0)")] System.Nullable<decimal> idMoneda, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tasa", DbType="Decimal(20,2)")] System.Nullable<decimal> tasa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, numeroFActura, idTipoFacturacion, numeroConector, facturadoA, nCF, fechaFActuracion, totalProductos, totalServicios, totalItems, subTotal, descuento, impuesto, total, idTipoPago, montoPagado, cambio, idMoneda, tasa, accion);
			return ((ISingleResult<SP_PROCESAR_INFORMACION_INFORMACION_VENTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_VALIDAR_ESTATUS_FACTURACION")]
		public ISingleResult<SP_VALIDAR_ESTATUS_FACTURACIONResult> SP_VALIDAR_ESTATUS_FACTURACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="VarChar(30)")] string numeroConector)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroConector);
			return ((ISingleResult<SP_VALIDAR_ESTATUS_FACTURACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_HISTORIAL_COTIZACIONES")]
		public ISingleResult<SP_HISTORIAL_COTIZACIONESResult> SP_HISTORIAL_COTIZACIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroCotizacion", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroCotizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="VarChar(30)")] string numeroConector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CotizadoA", DbType="VarChar(100)")] string cotizadoA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroServicios", DbType="Int")] System.Nullable<int> numeroServicios)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroCotizacion, numeroConector, cotizadoA, idUsuario, fechaDesde, fechaHasta, numeroPagina, numeroServicios);
			return ((ISingleResult<SP_HISTORIAL_COTIZACIONESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_BUSCA_ITEMS_AGREGADOS_COTIZACION")]
		public ISingleResult<SP_BUSCA_ITEMS_AGREGADOS_COTIZACIONResult> SP_BUSCA_ITEMS_AGREGADOS_COTIZACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroCotizacion", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroCotizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="VarChar(30)")] string numeroConector)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroCotizacion, numeroConector);
			return ((ISingleResult<SP_BUSCA_ITEMS_AGREGADOS_COTIZACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_PROCESAR_INFORMACION_HISTORIAL_COTIZACIONES")]
		public ISingleResult<SP_PROCESAR_INFORMACION_HISTORIAL_COTIZACIONESResult> SP_PROCESAR_INFORMACION_HISTORIAL_COTIZACIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroCotizacion", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroCotizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CotizadoA", DbType="VarChar(100)")] string cotizadoA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCotizacion", DbType="Date")] System.Nullable<System.DateTime> fechaCotizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalProductos", DbType="Int")] System.Nullable<int> totalProductos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalServicios", DbType="Int")] System.Nullable<int> totalServicios, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalItems", DbType="Int")] System.Nullable<int> totalItems, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubTotal", DbType="Decimal(20,2)")] System.Nullable<decimal> subTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="Decimal(20,2)")] System.Nullable<decimal> descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Impuesto", DbType="Decimal(20,2)")] System.Nullable<decimal> impuesto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Decimal(20,2)")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMoneda", DbType="Decimal(20,0)")] System.Nullable<decimal> idMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tasa", DbType="Decimal(20,2)")] System.Nullable<decimal> tasa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, numeroCotizacion, cotizadoA, fechaCotizacion, totalProductos, totalServicios, totalItems, subTotal, descuento, impuesto, total, idMoneda, tasa, accion);
			return ((ISingleResult<SP_PROCESAR_INFORMACION_HISTORIAL_COTIZACIONESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_HISTORIAL_FACTURACION")]
		public ISingleResult<SP_HISTORIAL_FACTURACIONResult> SP_HISTORIAL_FACTURACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="VarChar(30)")] string numeroConector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FacturadoA", DbType="VarChar(100)")] string facturadoA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Idusuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idusuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangoFechaDesde", DbType="Date")] System.Nullable<System.DateTime> rangoFechaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangoFechaHasta", DbType="Date")] System.Nullable<System.DateTime> rangoFechaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroFactura, numeroConector, facturadoA, idusuario, rangoFechaDesde, rangoFechaHasta, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_HISTORIAL_FACTURACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Historial.SP_MOSTRAR_ITEMS_AGREGADOS_FACTURA")]
		public ISingleResult<SP_MOSTRAR_ITEMS_AGREGADOS_FACTURAResult> SP_MOSTRAR_ITEMS_AGREGADOS_FACTURA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="VarChar(30)")] string numeroConector)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroFactura, numeroConector);
			return ((ISingleResult<SP_MOSTRAR_ITEMS_AGREGADOS_FACTURAResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_PROCESAR_INFORMACION_GANANCIA_VENTAResult
	{
		
		private System.Nullable<decimal> _IdUsuario;
		
		private System.Nullable<decimal> _IdEstatusFacturacion;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _NumeroFactura;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _IdCategoria;
		
		private System.Nullable<decimal> _IdTipoProducto;
		
		private System.Nullable<decimal> _PrecioCompra;
		
		private System.Nullable<decimal> _PrecioVenta;
		
		private System.Nullable<decimal> _CantidadVendida;
		
		private System.Nullable<decimal> _DescuentoAplicado;
		
		private System.Nullable<decimal> _TotalDescuentoAplicado;
		
		private System.Nullable<decimal> _TotalVenta;
		
		private System.Nullable<decimal> _TotalPrecioCompra;
		
		private System.Nullable<decimal> _Ganancia;
		
		public SP_PROCESAR_INFORMACION_GANANCIA_VENTAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstatusFacturacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdEstatusFacturacion
		{
			get
			{
				return this._IdEstatusFacturacion;
			}
			set
			{
				if ((this._IdEstatusFacturacion != value))
				{
					this._IdEstatusFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(100)")]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProducto", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoProducto
		{
			get
			{
				return this._IdTipoProducto;
			}
			set
			{
				if ((this._IdTipoProducto != value))
				{
					this._IdTipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompra", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioCompra
		{
			get
			{
				return this._PrecioCompra;
			}
			set
			{
				if ((this._PrecioCompra != value))
				{
					this._PrecioCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this._PrecioVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadVendida", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> CantidadVendida
		{
			get
			{
				return this._CantidadVendida;
			}
			set
			{
				if ((this._CantidadVendida != value))
				{
					this._CantidadVendida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescuentoAplicado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> DescuentoAplicado
		{
			get
			{
				return this._DescuentoAplicado;
			}
			set
			{
				if ((this._DescuentoAplicado != value))
				{
					this._DescuentoAplicado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDescuentoAplicado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalDescuentoAplicado
		{
			get
			{
				return this._TotalDescuentoAplicado;
			}
			set
			{
				if ((this._TotalDescuentoAplicado != value))
				{
					this._TotalDescuentoAplicado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalVenta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalVenta
		{
			get
			{
				return this._TotalVenta;
			}
			set
			{
				if ((this._TotalVenta != value))
				{
					this._TotalVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrecioCompra", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalPrecioCompra
		{
			get
			{
				return this._TotalPrecioCompra;
			}
			set
			{
				if ((this._TotalPrecioCompra != value))
				{
					this._TotalPrecioCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ganancia", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Ganancia
		{
			get
			{
				return this._Ganancia;
			}
			set
			{
				if ((this._Ganancia != value))
				{
					this._Ganancia = value;
				}
			}
		}
	}
	
	public partial class SP_PROCESAR_INFORMACION_INFORMACION_VENTASResult
	{
		
		private System.Nullable<decimal> _IdUsuario;
		
		private System.Nullable<decimal> _NumeroFActura;
		
		private System.Nullable<decimal> _IdTipoFacturacion;
		
		private string _NumeroConector;
		
		private string _FacturadoA;
		
		private string _NCF;
		
		private System.Nullable<System.DateTime> _FechaFActuracion;
		
		private System.Nullable<int> _TotalProductos;
		
		private System.Nullable<int> _TotalServicios;
		
		private System.Nullable<int> _TotalItems;
		
		private System.Nullable<decimal> _SubTotal;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private System.Nullable<decimal> _MontoPagado;
		
		private System.Nullable<decimal> _Cambio;
		
		private System.Nullable<decimal> _IdMoneda;
		
		private System.Nullable<decimal> _Tasa;
		
		public SP_PROCESAR_INFORMACION_INFORMACION_VENTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFActura", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroFActura
		{
			get
			{
				return this._NumeroFActura;
			}
			set
			{
				if ((this._NumeroFActura != value))
				{
					this._NumeroFActura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoFacturacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoFacturacion
		{
			get
			{
				return this._IdTipoFacturacion;
			}
			set
			{
				if ((this._IdTipoFacturacion != value))
				{
					this._IdTipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="VarChar(30)")]
		public string NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacturadoA", DbType="VarChar(100)")]
		public string FacturadoA
		{
			get
			{
				return this._FacturadoA;
			}
			set
			{
				if ((this._FacturadoA != value))
				{
					this._FacturadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCF", DbType="VarChar(30)")]
		public string NCF
		{
			get
			{
				return this._NCF;
			}
			set
			{
				if ((this._NCF != value))
				{
					this._NCF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFActuracion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaFActuracion
		{
			get
			{
				return this._FechaFActuracion;
			}
			set
			{
				if ((this._FechaFActuracion != value))
				{
					this._FechaFActuracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductos", DbType="Int")]
		public System.Nullable<int> TotalProductos
		{
			get
			{
				return this._TotalProductos;
			}
			set
			{
				if ((this._TotalProductos != value))
				{
					this._TotalProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServicios", DbType="Int")]
		public System.Nullable<int> TotalServicios
		{
			get
			{
				return this._TotalServicios;
			}
			set
			{
				if ((this._TotalServicios != value))
				{
					this._TotalServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int")]
		public System.Nullable<int> TotalItems
		{
			get
			{
				return this._TotalItems;
			}
			set
			{
				if ((this._TotalItems != value))
				{
					this._TotalItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this._SubTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cambio", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Cambio
		{
			get
			{
				return this._Cambio;
			}
			set
			{
				if ((this._Cambio != value))
				{
					this._Cambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMoneda", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMoneda
		{
			get
			{
				return this._IdMoneda;
			}
			set
			{
				if ((this._IdMoneda != value))
				{
					this._IdMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Tasa
		{
			get
			{
				return this._Tasa;
			}
			set
			{
				if ((this._Tasa != value))
				{
					this._Tasa = value;
				}
			}
		}
	}
	
	public partial class SP_VALIDAR_ESTATUS_FACTURACIONResult
	{
		
		private System.Nullable<decimal> _EstatusFacturacion;
		
		public SP_VALIDAR_ESTATUS_FACTURACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstatusFacturacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> EstatusFacturacion
		{
			get
			{
				return this._EstatusFacturacion;
			}
			set
			{
				if ((this._EstatusFacturacion != value))
				{
					this._EstatusFacturacion = value;
				}
			}
		}
	}
	
	public partial class SP_HISTORIAL_COTIZACIONESResult
	{
		
		private System.Nullable<decimal> _NumeroCotizacion;
		
		private string _NumeroConector;
		
		private string _CotizadoA;
		
		private System.Nullable<decimal> _CodigoCliente;
		
		private System.Nullable<decimal> _IdTipoFacturacion;
		
		private string _TipoFacturacion;
		
		private string _Comentario;
		
		private System.Nullable<int> _TotalProductos;
		
		private System.Nullable<int> _TotalServicios;
		
		private System.Nullable<int> _TotalItems;
		
		private System.Nullable<decimal> _SubTotal;
		
		private System.Nullable<decimal> _DescuentoTotal;
		
		private System.Nullable<decimal> _ImpuestoTotal;
		
		private System.Nullable<decimal> _TotalGeneral;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private string _TipoPago;
		
		private System.Nullable<decimal> _MontoPagado;
		
		private System.Nullable<decimal> _Cambio;
		
		private System.Nullable<decimal> _IdMoneda;
		
		private string _Moneda;
		
		private System.Nullable<decimal> _Tasa;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaCotizacion0;
		
		private string _FechaCotizacion;
		
		public SP_HISTORIAL_COTIZACIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCotizacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroCotizacion
		{
			get
			{
				return this._NumeroCotizacion;
			}
			set
			{
				if ((this._NumeroCotizacion != value))
				{
					this._NumeroCotizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="VarChar(30)")]
		public string NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CotizadoA", DbType="VarChar(100)")]
		public string CotizadoA
		{
			get
			{
				return this._CotizadoA;
			}
			set
			{
				if ((this._CotizadoA != value))
				{
					this._CotizadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCliente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> CodigoCliente
		{
			get
			{
				return this._CodigoCliente;
			}
			set
			{
				if ((this._CodigoCliente != value))
				{
					this._CodigoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoFacturacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoFacturacion
		{
			get
			{
				return this._IdTipoFacturacion;
			}
			set
			{
				if ((this._IdTipoFacturacion != value))
				{
					this._IdTipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoFacturacion", DbType="VarChar(100)")]
		public string TipoFacturacion
		{
			get
			{
				return this._TipoFacturacion;
			}
			set
			{
				if ((this._TipoFacturacion != value))
				{
					this._TipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(8000)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductos", DbType="Int")]
		public System.Nullable<int> TotalProductos
		{
			get
			{
				return this._TotalProductos;
			}
			set
			{
				if ((this._TotalProductos != value))
				{
					this._TotalProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServicios", DbType="Int")]
		public System.Nullable<int> TotalServicios
		{
			get
			{
				return this._TotalServicios;
			}
			set
			{
				if ((this._TotalServicios != value))
				{
					this._TotalServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int")]
		public System.Nullable<int> TotalItems
		{
			get
			{
				return this._TotalItems;
			}
			set
			{
				if ((this._TotalItems != value))
				{
					this._TotalItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this._SubTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescuentoTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> DescuentoTotal
		{
			get
			{
				return this._DescuentoTotal;
			}
			set
			{
				if ((this._DescuentoTotal != value))
				{
					this._DescuentoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpuestoTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ImpuestoTotal
		{
			get
			{
				return this._ImpuestoTotal;
			}
			set
			{
				if ((this._ImpuestoTotal != value))
				{
					this._ImpuestoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalGeneral", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalGeneral
		{
			get
			{
				return this._TotalGeneral;
			}
			set
			{
				if ((this._TotalGeneral != value))
				{
					this._TotalGeneral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPago", DbType="VarChar(100)")]
		public string TipoPago
		{
			get
			{
				return this._TipoPago;
			}
			set
			{
				if ((this._TipoPago != value))
				{
					this._TipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cambio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Cambio
		{
			get
			{
				return this._Cambio;
			}
			set
			{
				if ((this._Cambio != value))
				{
					this._Cambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMoneda", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMoneda
		{
			get
			{
				return this._IdMoneda;
			}
			set
			{
				if ((this._IdMoneda != value))
				{
					this._IdMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(100)")]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this._Moneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Tasa
		{
			get
			{
				return this._Tasa;
			}
			set
			{
				if ((this._Tasa != value))
				{
					this._Tasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCotizacion0", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCotizacion0
		{
			get
			{
				return this._FechaCotizacion0;
			}
			set
			{
				if ((this._FechaCotizacion0 != value))
				{
					this._FechaCotizacion0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCotizacion", DbType="NVarChar(4000)")]
		public string FechaCotizacion
		{
			get
			{
				return this._FechaCotizacion;
			}
			set
			{
				if ((this._FechaCotizacion != value))
				{
					this._FechaCotizacion = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_ITEMS_AGREGADOS_COTIZACIONResult
	{
		
		private System.Nullable<decimal> _NumeroCotizacion;
		
		private string _NumeroConector;
		
		private string _CotizacoA;
		
		private string _FechaCotizacion;
		
		private System.Nullable<int> _TotalProductos;
		
		private System.Nullable<int> _TotalServicios;
		
		private System.Nullable<int> _TotalItems;
		
		private string _DescripcionRespaldo;
		
		private System.Nullable<decimal> _IdTipoProductoRespaldo;
		
		private string _TipoProducto;
		
		private System.Nullable<decimal> _Precio;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _SubTotal;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total;
		
		public SP_BUSCA_ITEMS_AGREGADOS_COTIZACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCotizacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroCotizacion
		{
			get
			{
				return this._NumeroCotizacion;
			}
			set
			{
				if ((this._NumeroCotizacion != value))
				{
					this._NumeroCotizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="VarChar(30)")]
		public string NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CotizacoA", DbType="VarChar(100)")]
		public string CotizacoA
		{
			get
			{
				return this._CotizacoA;
			}
			set
			{
				if ((this._CotizacoA != value))
				{
					this._CotizacoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCotizacion", DbType="NVarChar(4000)")]
		public string FechaCotizacion
		{
			get
			{
				return this._FechaCotizacion;
			}
			set
			{
				if ((this._FechaCotizacion != value))
				{
					this._FechaCotizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductos", DbType="Int")]
		public System.Nullable<int> TotalProductos
		{
			get
			{
				return this._TotalProductos;
			}
			set
			{
				if ((this._TotalProductos != value))
				{
					this._TotalProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServicios", DbType="Int")]
		public System.Nullable<int> TotalServicios
		{
			get
			{
				return this._TotalServicios;
			}
			set
			{
				if ((this._TotalServicios != value))
				{
					this._TotalServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int")]
		public System.Nullable<int> TotalItems
		{
			get
			{
				return this._TotalItems;
			}
			set
			{
				if ((this._TotalItems != value))
				{
					this._TotalItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionRespaldo", DbType="VarChar(200)")]
		public string DescripcionRespaldo
		{
			get
			{
				return this._DescripcionRespaldo;
			}
			set
			{
				if ((this._DescripcionRespaldo != value))
				{
					this._DescripcionRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProductoRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoProductoRespaldo
		{
			get
			{
				return this._IdTipoProductoRespaldo;
			}
			set
			{
				if ((this._IdTipoProductoRespaldo != value))
				{
					this._IdTipoProductoRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProducto", DbType="VarChar(100)")]
		public string TipoProducto
		{
			get
			{
				return this._TipoProducto;
			}
			set
			{
				if ((this._TipoProducto != value))
				{
					this._TipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this._SubTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class SP_PROCESAR_INFORMACION_HISTORIAL_COTIZACIONESResult
	{
		
		private System.Nullable<decimal> _IdUsuario;
		
		private System.Nullable<decimal> _NumeroCotizacion;
		
		private string _CotizadoA;
		
		private System.Nullable<System.DateTime> _FechaCotizacion;
		
		private System.Nullable<int> _TotalProductos;
		
		private System.Nullable<int> _TotalServicios;
		
		private System.Nullable<int> _TotalItems;
		
		private System.Nullable<decimal> _SubTotal;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<decimal> _IdMoneda;
		
		private System.Nullable<decimal> _Tasa;
		
		public SP_PROCESAR_INFORMACION_HISTORIAL_COTIZACIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCotizacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroCotizacion
		{
			get
			{
				return this._NumeroCotizacion;
			}
			set
			{
				if ((this._NumeroCotizacion != value))
				{
					this._NumeroCotizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CotizadoA", DbType="VarChar(100)")]
		public string CotizadoA
		{
			get
			{
				return this._CotizadoA;
			}
			set
			{
				if ((this._CotizadoA != value))
				{
					this._CotizadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCotizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCotizacion
		{
			get
			{
				return this._FechaCotizacion;
			}
			set
			{
				if ((this._FechaCotizacion != value))
				{
					this._FechaCotizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductos", DbType="Int")]
		public System.Nullable<int> TotalProductos
		{
			get
			{
				return this._TotalProductos;
			}
			set
			{
				if ((this._TotalProductos != value))
				{
					this._TotalProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServicios", DbType="Int")]
		public System.Nullable<int> TotalServicios
		{
			get
			{
				return this._TotalServicios;
			}
			set
			{
				if ((this._TotalServicios != value))
				{
					this._TotalServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int")]
		public System.Nullable<int> TotalItems
		{
			get
			{
				return this._TotalItems;
			}
			set
			{
				if ((this._TotalItems != value))
				{
					this._TotalItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this._SubTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMoneda", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMoneda
		{
			get
			{
				return this._IdMoneda;
			}
			set
			{
				if ((this._IdMoneda != value))
				{
					this._IdMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Tasa
		{
			get
			{
				return this._Tasa;
			}
			set
			{
				if ((this._Tasa != value))
				{
					this._Tasa = value;
				}
			}
		}
	}
	
	public partial class SP_HISTORIAL_FACTURACIONResult
	{
		
		private decimal _NumeroFactura;
		
		private string _NumeroConector;
		
		private string _FacturadoA;
		
		private System.Nullable<decimal> _CodigoCliente;
		
		private decimal _IdTipoFacturacion;
		
		private string _TipoFacturacion;
		
		private string _Comentario;
		
		private System.Nullable<int> _TotalProductos;
		
		private System.Nullable<int> _TotalServicios;
		
		private System.Nullable<int> _TotalItems;
		
		private System.Nullable<decimal> _SubTotal;
		
		private System.Nullable<decimal> _DescuentoTotal;
		
		private System.Nullable<decimal> _ImpuestoTotal;
		
		private System.Nullable<decimal> _TotalGeneral;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private string _TipoPago;
		
		private System.Nullable<decimal> _MontoPagado;
		
		private System.Nullable<decimal> _Cambio;
		
		private System.Nullable<decimal> _IdMoneda;
		
		private string _Moneda;
		
		private System.Nullable<decimal> _Tasa;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaFacturacion0;
		
		private string _FechaFacturacion;
		
		private string _Hora;
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _NCF;
		
		private string _ValidoHasta;
		
		private string _NumeroComprobante;
		
		private System.Nullable<bool> _EfectivoMixto0;
		
		private string _EfectivoMixto;
		
		private System.Nullable<decimal> _MontoEfectivoMixto;
		
		private System.Nullable<bool> _ChequeMixto0;
		
		private string _ChequeMixto;
		
		private System.Nullable<decimal> _MontoChequeMixto;
		
		private System.Nullable<bool> _TransferenciaMixto0;
		
		private string _TransferenciaMixto;
		
		private System.Nullable<decimal> _MontoTransferenciaMixto;
		
		private System.Nullable<bool> _DepositoMixto0;
		
		private string _DepositoMixto;
		
		private System.Nullable<decimal> _MontoDepositoMixto;
		
		private System.Nullable<bool> _TarjetaMixto0;
		
		private string _TarjetaMixto;
		
		private System.Nullable<decimal> _MontoTarjetaMixto;
		
		private string _PagoMixto;
		
		private System.Nullable<decimal> _CapitalInvertido;
		
		private System.Nullable<decimal> _GananciaVenta;
		
		private System.Nullable<decimal> _Ganancia;
		
		public SP_HISTORIAL_FACTURACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0) NOT NULL")]
		public decimal NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacturadoA", DbType="VarChar(100)")]
		public string FacturadoA
		{
			get
			{
				return this._FacturadoA;
			}
			set
			{
				if ((this._FacturadoA != value))
				{
					this._FacturadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCliente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> CodigoCliente
		{
			get
			{
				return this._CodigoCliente;
			}
			set
			{
				if ((this._CodigoCliente != value))
				{
					this._CodigoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoFacturacion", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdTipoFacturacion
		{
			get
			{
				return this._IdTipoFacturacion;
			}
			set
			{
				if ((this._IdTipoFacturacion != value))
				{
					this._IdTipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoFacturacion", DbType="VarChar(100)")]
		public string TipoFacturacion
		{
			get
			{
				return this._TipoFacturacion;
			}
			set
			{
				if ((this._TipoFacturacion != value))
				{
					this._TipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(8000)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductos", DbType="Int")]
		public System.Nullable<int> TotalProductos
		{
			get
			{
				return this._TotalProductos;
			}
			set
			{
				if ((this._TotalProductos != value))
				{
					this._TotalProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServicios", DbType="Int")]
		public System.Nullable<int> TotalServicios
		{
			get
			{
				return this._TotalServicios;
			}
			set
			{
				if ((this._TotalServicios != value))
				{
					this._TotalServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int")]
		public System.Nullable<int> TotalItems
		{
			get
			{
				return this._TotalItems;
			}
			set
			{
				if ((this._TotalItems != value))
				{
					this._TotalItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this._SubTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescuentoTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> DescuentoTotal
		{
			get
			{
				return this._DescuentoTotal;
			}
			set
			{
				if ((this._DescuentoTotal != value))
				{
					this._DescuentoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpuestoTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ImpuestoTotal
		{
			get
			{
				return this._ImpuestoTotal;
			}
			set
			{
				if ((this._ImpuestoTotal != value))
				{
					this._ImpuestoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalGeneral", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalGeneral
		{
			get
			{
				return this._TotalGeneral;
			}
			set
			{
				if ((this._TotalGeneral != value))
				{
					this._TotalGeneral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPago", DbType="VarChar(100)")]
		public string TipoPago
		{
			get
			{
				return this._TipoPago;
			}
			set
			{
				if ((this._TipoPago != value))
				{
					this._TipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cambio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Cambio
		{
			get
			{
				return this._Cambio;
			}
			set
			{
				if ((this._Cambio != value))
				{
					this._Cambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMoneda", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMoneda
		{
			get
			{
				return this._IdMoneda;
			}
			set
			{
				if ((this._IdMoneda != value))
				{
					this._IdMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(100)")]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this._Moneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Tasa
		{
			get
			{
				return this._Tasa;
			}
			set
			{
				if ((this._Tasa != value))
				{
					this._Tasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFacturacion0", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFacturacion0
		{
			get
			{
				return this._FechaFacturacion0;
			}
			set
			{
				if ((this._FechaFacturacion0 != value))
				{
					this._FechaFacturacion0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFacturacion", DbType="NVarChar(4000)")]
		public string FechaFacturacion
		{
			get
			{
				return this._FechaFacturacion;
			}
			set
			{
				if ((this._FechaFacturacion != value))
				{
					this._FechaFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="NVarChar(4000)")]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCF", DbType="VarChar(100)")]
		public string NCF
		{
			get
			{
				return this._NCF;
			}
			set
			{
				if ((this._NCF != value))
				{
					this._NCF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidoHasta", DbType="VarChar(50)")]
		public string ValidoHasta
		{
			get
			{
				return this._ValidoHasta;
			}
			set
			{
				if ((this._ValidoHasta != value))
				{
					this._ValidoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(30)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EfectivoMixto0", DbType="Bit")]
		public System.Nullable<bool> EfectivoMixto0
		{
			get
			{
				return this._EfectivoMixto0;
			}
			set
			{
				if ((this._EfectivoMixto0 != value))
				{
					this._EfectivoMixto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EfectivoMixto", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string EfectivoMixto
		{
			get
			{
				return this._EfectivoMixto;
			}
			set
			{
				if ((this._EfectivoMixto != value))
				{
					this._EfectivoMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoEfectivoMixto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoEfectivoMixto
		{
			get
			{
				return this._MontoEfectivoMixto;
			}
			set
			{
				if ((this._MontoEfectivoMixto != value))
				{
					this._MontoEfectivoMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChequeMixto0", DbType="Bit")]
		public System.Nullable<bool> ChequeMixto0
		{
			get
			{
				return this._ChequeMixto0;
			}
			set
			{
				if ((this._ChequeMixto0 != value))
				{
					this._ChequeMixto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChequeMixto", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ChequeMixto
		{
			get
			{
				return this._ChequeMixto;
			}
			set
			{
				if ((this._ChequeMixto != value))
				{
					this._ChequeMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoChequeMixto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoChequeMixto
		{
			get
			{
				return this._MontoChequeMixto;
			}
			set
			{
				if ((this._MontoChequeMixto != value))
				{
					this._MontoChequeMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferenciaMixto0", DbType="Bit")]
		public System.Nullable<bool> TransferenciaMixto0
		{
			get
			{
				return this._TransferenciaMixto0;
			}
			set
			{
				if ((this._TransferenciaMixto0 != value))
				{
					this._TransferenciaMixto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferenciaMixto", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string TransferenciaMixto
		{
			get
			{
				return this._TransferenciaMixto;
			}
			set
			{
				if ((this._TransferenciaMixto != value))
				{
					this._TransferenciaMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoTransferenciaMixto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoTransferenciaMixto
		{
			get
			{
				return this._MontoTransferenciaMixto;
			}
			set
			{
				if ((this._MontoTransferenciaMixto != value))
				{
					this._MontoTransferenciaMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepositoMixto0", DbType="Bit")]
		public System.Nullable<bool> DepositoMixto0
		{
			get
			{
				return this._DepositoMixto0;
			}
			set
			{
				if ((this._DepositoMixto0 != value))
				{
					this._DepositoMixto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepositoMixto", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string DepositoMixto
		{
			get
			{
				return this._DepositoMixto;
			}
			set
			{
				if ((this._DepositoMixto != value))
				{
					this._DepositoMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoDepositoMixto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoDepositoMixto
		{
			get
			{
				return this._MontoDepositoMixto;
			}
			set
			{
				if ((this._MontoDepositoMixto != value))
				{
					this._MontoDepositoMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarjetaMixto0", DbType="Bit")]
		public System.Nullable<bool> TarjetaMixto0
		{
			get
			{
				return this._TarjetaMixto0;
			}
			set
			{
				if ((this._TarjetaMixto0 != value))
				{
					this._TarjetaMixto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarjetaMixto", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string TarjetaMixto
		{
			get
			{
				return this._TarjetaMixto;
			}
			set
			{
				if ((this._TarjetaMixto != value))
				{
					this._TarjetaMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoTarjetaMixto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoTarjetaMixto
		{
			get
			{
				return this._MontoTarjetaMixto;
			}
			set
			{
				if ((this._MontoTarjetaMixto != value))
				{
					this._MontoTarjetaMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagoMixto", DbType="VarChar(679) NOT NULL", CanBeNull=false)]
		public string PagoMixto
		{
			get
			{
				return this._PagoMixto;
			}
			set
			{
				if ((this._PagoMixto != value))
				{
					this._PagoMixto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapitalInvertido", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CapitalInvertido
		{
			get
			{
				return this._CapitalInvertido;
			}
			set
			{
				if ((this._CapitalInvertido != value))
				{
					this._CapitalInvertido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GananciaVenta", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GananciaVenta
		{
			get
			{
				return this._GananciaVenta;
			}
			set
			{
				if ((this._GananciaVenta != value))
				{
					this._GananciaVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ganancia", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Ganancia
		{
			get
			{
				return this._Ganancia;
			}
			set
			{
				if ((this._Ganancia != value))
				{
					this._Ganancia = value;
				}
			}
		}
	}
	
	public partial class SP_MOSTRAR_ITEMS_AGREGADOS_FACTURAResult
	{
		
		private decimal _NumeroFactura;
		
		private string _NumeroConector;
		
		private decimal _IdTipoFacturacion;
		
		private string _TipoFacturacion;
		
		private string _Anulada;
		
		private string _FacturadoA;
		
		private string _FechaFacturacion;
		
		private string _HoraFacturacion;
		
		private System.Nullable<int> _TotalProductos;
		
		private System.Nullable<int> _TotalServicios;
		
		private System.Nullable<int> _TotalItems;
		
		private string _Coenectordetalle;
		
		private string _Tipo;
		
		private System.Nullable<decimal> _Precio;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<int> _PorcientoImpuesto;
		
		private System.Nullable<decimal> _SubTotal;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<decimal> _IdRegistroRespaldo;
		
		private string _NumeroConectorItemRespaldo;
		
		private System.Nullable<decimal> _IdTipoProductoRespaldo;
		
		private System.Nullable<decimal> _IdCategoriaRespaldo;
		
		private System.Nullable<decimal> _IdMarcaRespaldo;
		
		private System.Nullable<decimal> _IdTipoSuplidorRespaldo;
		
		private System.Nullable<decimal> _IdSuplidorRespaldo;
		
		private string _Descripcion;
		
		private string _CodigoBarraRespaldo;
		
		private string _ReferenciaRespaldo;
		
		private string _NumeroSeguimientoRespaldo;
		
		private string _CodigoProductoRespaldo;
		
		private System.Nullable<decimal> _PrecioCompraRespaldo;
		
		private System.Nullable<decimal> _PrecioVentaRespaldo;
		
		private System.Nullable<decimal> _StockRespaldo;
		
		private System.Nullable<decimal> _StockMinimoRespaldo;
		
		private string _UnidadMedidaRespaldo;
		
		private string _ModeloRespaldo;
		
		private string _ColorRespaldo;
		
		private string _CondicionRespaldo;
		
		private string _CapacidadRespaldo;
		
		private System.Nullable<bool> _AplicaParaImpuestoRespaldo;
		
		private System.Nullable<bool> _TieneImagenRespaldo;
		
		private System.Nullable<bool> _LlevaGarantiaRespaldo;
		
		private System.Nullable<decimal> _IdTipoGarantiaRespaldo;
		
		private System.Nullable<int> _TiempoGarantiaRespaldo;
		
		private string _ComentarioItemRespaldo;
		
		private System.Nullable<decimal> _UsuarioAdicionaRespaldo;
		
		private System.Nullable<System.DateTime> _FechaAdicionaRespaldo;
		
		private System.Nullable<decimal> _UsuarioModificaRespaldo;
		
		private System.Nullable<System.DateTime> _FechaModificaRespaldo;
		
		private System.Nullable<System.DateTime> _FechaIngresoRespaldo;
		
		public SP_MOSTRAR_ITEMS_AGREGADOS_FACTURAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0) NOT NULL")]
		public decimal NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoFacturacion", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdTipoFacturacion
		{
			get
			{
				return this._IdTipoFacturacion;
			}
			set
			{
				if ((this._IdTipoFacturacion != value))
				{
					this._IdTipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoFacturacion", DbType="VarChar(100)")]
		public string TipoFacturacion
		{
			get
			{
				return this._TipoFacturacion;
			}
			set
			{
				if ((this._TipoFacturacion != value))
				{
					this._TipoFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anulada", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Anulada
		{
			get
			{
				return this._Anulada;
			}
			set
			{
				if ((this._Anulada != value))
				{
					this._Anulada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacturadoA", DbType="VarChar(100)")]
		public string FacturadoA
		{
			get
			{
				return this._FacturadoA;
			}
			set
			{
				if ((this._FacturadoA != value))
				{
					this._FacturadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFacturacion", DbType="NVarChar(4000)")]
		public string FechaFacturacion
		{
			get
			{
				return this._FechaFacturacion;
			}
			set
			{
				if ((this._FechaFacturacion != value))
				{
					this._FechaFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFacturacion", DbType="NVarChar(4000)")]
		public string HoraFacturacion
		{
			get
			{
				return this._HoraFacturacion;
			}
			set
			{
				if ((this._HoraFacturacion != value))
				{
					this._HoraFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductos", DbType="Int")]
		public System.Nullable<int> TotalProductos
		{
			get
			{
				return this._TotalProductos;
			}
			set
			{
				if ((this._TotalProductos != value))
				{
					this._TotalProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServicios", DbType="Int")]
		public System.Nullable<int> TotalServicios
		{
			get
			{
				return this._TotalServicios;
			}
			set
			{
				if ((this._TotalServicios != value))
				{
					this._TotalServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int")]
		public System.Nullable<int> TotalItems
		{
			get
			{
				return this._TotalItems;
			}
			set
			{
				if ((this._TotalItems != value))
				{
					this._TotalItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coenectordetalle", DbType="VarChar(30)")]
		public string Coenectordetalle
		{
			get
			{
				return this._Coenectordetalle;
			}
			set
			{
				if ((this._Coenectordetalle != value))
				{
					this._Coenectordetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcientoImpuesto", DbType="Int")]
		public System.Nullable<int> PorcientoImpuesto
		{
			get
			{
				return this._PorcientoImpuesto;
			}
			set
			{
				if ((this._PorcientoImpuesto != value))
				{
					this._PorcientoImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this._SubTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdRegistroRespaldo
		{
			get
			{
				return this._IdRegistroRespaldo;
			}
			set
			{
				if ((this._IdRegistroRespaldo != value))
				{
					this._IdRegistroRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConectorItemRespaldo", DbType="VarChar(30)")]
		public string NumeroConectorItemRespaldo
		{
			get
			{
				return this._NumeroConectorItemRespaldo;
			}
			set
			{
				if ((this._NumeroConectorItemRespaldo != value))
				{
					this._NumeroConectorItemRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProductoRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoProductoRespaldo
		{
			get
			{
				return this._IdTipoProductoRespaldo;
			}
			set
			{
				if ((this._IdTipoProductoRespaldo != value))
				{
					this._IdTipoProductoRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoriaRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCategoriaRespaldo
		{
			get
			{
				return this._IdCategoriaRespaldo;
			}
			set
			{
				if ((this._IdCategoriaRespaldo != value))
				{
					this._IdCategoriaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMarcaRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMarcaRespaldo
		{
			get
			{
				return this._IdMarcaRespaldo;
			}
			set
			{
				if ((this._IdMarcaRespaldo != value))
				{
					this._IdMarcaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoSuplidorRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoSuplidorRespaldo
		{
			get
			{
				return this._IdTipoSuplidorRespaldo;
			}
			set
			{
				if ((this._IdTipoSuplidorRespaldo != value))
				{
					this._IdTipoSuplidorRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSuplidorRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdSuplidorRespaldo
		{
			get
			{
				return this._IdSuplidorRespaldo;
			}
			set
			{
				if ((this._IdSuplidorRespaldo != value))
				{
					this._IdSuplidorRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoBarraRespaldo", DbType="VarChar(50)")]
		public string CodigoBarraRespaldo
		{
			get
			{
				return this._CodigoBarraRespaldo;
			}
			set
			{
				if ((this._CodigoBarraRespaldo != value))
				{
					this._CodigoBarraRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenciaRespaldo", DbType="VarChar(50)")]
		public string ReferenciaRespaldo
		{
			get
			{
				return this._ReferenciaRespaldo;
			}
			set
			{
				if ((this._ReferenciaRespaldo != value))
				{
					this._ReferenciaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroSeguimientoRespaldo", DbType="VarChar(50)")]
		public string NumeroSeguimientoRespaldo
		{
			get
			{
				return this._NumeroSeguimientoRespaldo;
			}
			set
			{
				if ((this._NumeroSeguimientoRespaldo != value))
				{
					this._NumeroSeguimientoRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProductoRespaldo", DbType="VarChar(50)")]
		public string CodigoProductoRespaldo
		{
			get
			{
				return this._CodigoProductoRespaldo;
			}
			set
			{
				if ((this._CodigoProductoRespaldo != value))
				{
					this._CodigoProductoRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompraRespaldo", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioCompraRespaldo
		{
			get
			{
				return this._PrecioCompraRespaldo;
			}
			set
			{
				if ((this._PrecioCompraRespaldo != value))
				{
					this._PrecioCompraRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaRespaldo", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioVentaRespaldo
		{
			get
			{
				return this._PrecioVentaRespaldo;
			}
			set
			{
				if ((this._PrecioVentaRespaldo != value))
				{
					this._PrecioVentaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> StockRespaldo
		{
			get
			{
				return this._StockRespaldo;
			}
			set
			{
				if ((this._StockRespaldo != value))
				{
					this._StockRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimoRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> StockMinimoRespaldo
		{
			get
			{
				return this._StockMinimoRespaldo;
			}
			set
			{
				if ((this._StockMinimoRespaldo != value))
				{
					this._StockMinimoRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadMedidaRespaldo", DbType="VarChar(100)")]
		public string UnidadMedidaRespaldo
		{
			get
			{
				return this._UnidadMedidaRespaldo;
			}
			set
			{
				if ((this._UnidadMedidaRespaldo != value))
				{
					this._UnidadMedidaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModeloRespaldo", DbType="VarChar(100)")]
		public string ModeloRespaldo
		{
			get
			{
				return this._ModeloRespaldo;
			}
			set
			{
				if ((this._ModeloRespaldo != value))
				{
					this._ModeloRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorRespaldo", DbType="VarChar(100)")]
		public string ColorRespaldo
		{
			get
			{
				return this._ColorRespaldo;
			}
			set
			{
				if ((this._ColorRespaldo != value))
				{
					this._ColorRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CondicionRespaldo", DbType="VarChar(100)")]
		public string CondicionRespaldo
		{
			get
			{
				return this._CondicionRespaldo;
			}
			set
			{
				if ((this._CondicionRespaldo != value))
				{
					this._CondicionRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacidadRespaldo", DbType="VarChar(100)")]
		public string CapacidadRespaldo
		{
			get
			{
				return this._CapacidadRespaldo;
			}
			set
			{
				if ((this._CapacidadRespaldo != value))
				{
					this._CapacidadRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AplicaParaImpuestoRespaldo", DbType="Bit")]
		public System.Nullable<bool> AplicaParaImpuestoRespaldo
		{
			get
			{
				return this._AplicaParaImpuestoRespaldo;
			}
			set
			{
				if ((this._AplicaParaImpuestoRespaldo != value))
				{
					this._AplicaParaImpuestoRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieneImagenRespaldo", DbType="Bit")]
		public System.Nullable<bool> TieneImagenRespaldo
		{
			get
			{
				return this._TieneImagenRespaldo;
			}
			set
			{
				if ((this._TieneImagenRespaldo != value))
				{
					this._TieneImagenRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaGarantiaRespaldo", DbType="Bit")]
		public System.Nullable<bool> LlevaGarantiaRespaldo
		{
			get
			{
				return this._LlevaGarantiaRespaldo;
			}
			set
			{
				if ((this._LlevaGarantiaRespaldo != value))
				{
					this._LlevaGarantiaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoGarantiaRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoGarantiaRespaldo
		{
			get
			{
				return this._IdTipoGarantiaRespaldo;
			}
			set
			{
				if ((this._IdTipoGarantiaRespaldo != value))
				{
					this._IdTipoGarantiaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiempoGarantiaRespaldo", DbType="Int")]
		public System.Nullable<int> TiempoGarantiaRespaldo
		{
			get
			{
				return this._TiempoGarantiaRespaldo;
			}
			set
			{
				if ((this._TiempoGarantiaRespaldo != value))
				{
					this._TiempoGarantiaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioItemRespaldo", DbType="VarChar(8000)")]
		public string ComentarioItemRespaldo
		{
			get
			{
				return this._ComentarioItemRespaldo;
			}
			set
			{
				if ((this._ComentarioItemRespaldo != value))
				{
					this._ComentarioItemRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdicionaRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdicionaRespaldo
		{
			get
			{
				return this._UsuarioAdicionaRespaldo;
			}
			set
			{
				if ((this._UsuarioAdicionaRespaldo != value))
				{
					this._UsuarioAdicionaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdicionaRespaldo", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdicionaRespaldo
		{
			get
			{
				return this._FechaAdicionaRespaldo;
			}
			set
			{
				if ((this._FechaAdicionaRespaldo != value))
				{
					this._FechaAdicionaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModificaRespaldo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModificaRespaldo
		{
			get
			{
				return this._UsuarioModificaRespaldo;
			}
			set
			{
				if ((this._UsuarioModificaRespaldo != value))
				{
					this._UsuarioModificaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificaRespaldo", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificaRespaldo
		{
			get
			{
				return this._FechaModificaRespaldo;
			}
			set
			{
				if ((this._FechaModificaRespaldo != value))
				{
					this._FechaModificaRespaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngresoRespaldo", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaIngresoRespaldo
		{
			get
			{
				return this._FechaIngresoRespaldo;
			}
			set
			{
				if ((this._FechaIngresoRespaldo != value))
				{
					this._FechaIngresoRespaldo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
