<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionContabilidadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;Persist Security Info=True;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="Contabilidad.SP_BUSCA_REGISTROS_CATALOGO_CUENTAS" Method="SP_BUSCA_REGISTROS_CATALOGO_CUENTAS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CuentaContable" Parameter="cuentaContable" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DescripcionCuenta" Parameter="descripcionCuenta" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="CuentaDecarge" Parameter="cuentaDecarge" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_REGISTROS_CATALOGO_CUENTASResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NombreCuenta" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdOrigenCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Origen" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdClaseCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Clase" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdAceptaMovimientoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AceptaMovimiento" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CodAnexo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaDescargo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CuentaPresupuesto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AuxiliarPresupuesto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CuentaAnterior" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_MANTENIMIENTO_CATALOGO_CUENTA" Method="SP_MANTENIMIENTO_CATALOGO_CUENTA">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cuenta" Parameter="cuenta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdOrigenCuenta" Parameter="idOrigenCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdTipoCuenta" Parameter="idTipoCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdClaseCuenta" Parameter="idClaseCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdAceptaMovimientoCuenta" Parameter="idAceptaMovimientoCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodAnexo" Parameter="codAnexo" Type="System.Int32" DbType="Int" />
    <Parameter Name="CuentaDescargo" Parameter="cuentaDescargo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CuentaPresupuesto" Parameter="cuentaPresupuesto" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="AuxiliarPresupuesto" Parameter="auxiliarPresupuesto" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CuentaAnterior" Parameter="cuentaAnterior" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CATALOGO_CUENTAResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdOrigenCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdClaseCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdAceptaMovimientoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodAnexo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaDescargo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CuentaPresupuesto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AuxiliarPresupuesto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CuentaAnterior" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_BUSCA_BANCOS" Method="SP_BUSCA_BANCOS">
    <Parameter Name="IdBanco" Parameter="idBanco" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Banco" Parameter="banco" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PorDefecto" Parameter="porDefecto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_BANCOSResult">
      <Column Name="IdBanco" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Banco" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="PorDefecto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_MANTENIMIENTO_BANCOS" Method="SP_MANTENIMIENTO_BANCOS">
    <Parameter Name="IdBanco" Parameter="idBanco" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Banco" Parameter="banco" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorDefecto" Parameter="porDefecto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_BANCOSResult">
      <Column Name="IdBanco" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Banco" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_BUSCA_CONCEPTOS_CUENTAS_PROCESOS" Method="SP_BUSCA_CONCEPTOS_CUENTAS_PROCESOS">
    <Parameter Name="IdConceptoCuentasProcesos" Parameter="idConceptoCuentasProcesos" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CONCEPTOS_CUENTAS_PROCESOSResult">
      <Column Name="IdConceptoCuentasProcesos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_GUARDAR_CUENTAS_MOVIMIENTOS" Method="SP_GUARDAR_CUENTAS_MOVIMIENTOS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(25,0)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="IdTipoCuenta" Parameter="idTipoCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdModulo" Parameter="idModulo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Conector" Parameter="conector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Banco" Parameter="banco" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cuenta" Parameter="cuenta" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Valor" Parameter="valor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdOrigen" Parameter="idOrigen" Type="System.Int32" DbType="Int" />
    <Parameter Name="ConceptoCuenta" Parameter="conceptoCuenta" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="NumeroRelacionado" Parameter="numeroRelacionado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdClaseCuenta" Parameter="idClaseCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCuentaContable" Parameter="idCuentaContable" Type="System.Decimal" DbType="Decimal(25,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_CUENTAS_MOVIMIENTOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IdTipoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdModulo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Conector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Banco" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdOrigen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConceptoCuenta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="NumeroRelacionado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdClaseCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCuentaContable" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_SACAR_INFORMACION_CUENTAS_MOVIMIENTOS" Method="SP_SACAR_INFORMACION_CUENTAS_MOVIMIENTOS">
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(2)" />
    <ElementType Name="SP_SACAR_INFORMACION_CUENTAS_MOVIMIENTOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IdTipoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoCuenta" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdModulo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Modulo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Conector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Banco" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreBanco" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdOrigen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrigenCuenta" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ConceptoCuenta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="NumeroRelacionado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdClaseCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaseCuenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCuentaContable" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="CuentaDescargo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>