<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionCajaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Caja.SP_ESTATUS_CAJA" Method="SP_ESTATUS_CAJA">
    <ElementType Name="SP_ESTATUS_CAJAResult">
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Caja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_AFECTAR_CAJA_GENERAL" Method="SP_AFECTAR_CAJA_GENERAL">
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoActual" Parameter="montoActual" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_AFECTAR_CAJA_GENERALResult">
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_GUARDAR_HISTORIAL_CAJA" Method="SP_GUARDAR_HISTORIAL_CAJA">
    <Parameter Name="IdHistorialCaja" Parameter="idHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_HISTORIAL_CAJAResult">
      <Column Name="IdHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MANTENIMIENTO_HISTORIAL_CAJA" Method="SP_MANTENIMIENTO_HISTORIAL_CAJA">
    <Parameter Name="IdHistorialCaja" Parameter="idHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORIAL_CAJAResult">
      <Column Name="IdHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_BUSCA_HISTORIAL_CAJA" Method="SP_BUSCA_HISTORIAL_CAJA">
    <Parameter Name="IdHistorialCaja" Parameter="idHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BUSCA_HISTORIAL_CAJAResult">
      <Column Name="IdHistorialCaja" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GENERAR_REPORTE_CUADRE_CAJA" Method="SP_GENERAR_REPORTE_CUADRE_CAJA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_GENERAR_REPORTE_CUADRE_CAJAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCaja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaProcesado0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaProcesado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaDesde0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaHasta0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagran" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LogoEmpresa" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="MontoTotal" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cantidadmovimientos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_BUSCAR_MONTO_INICIAL_CAJA" Method="SP_BUSCAR_MONTO_INICIAL_CAJA">
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCAR_MONTO_INICIAL_CAJAResult">
      <Column Name="IdCaja" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MontoInicialCaja" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MODIFICAR_MONTO_INICIAL_CAJA" Method="SP_MODIFICAR_MONTO_INICIAL_CAJA">
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Int32" DbType="Int" />
    <Parameter Name="MontoInicialCaja" Parameter="montoInicialCaja" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_MONTO_INICIAL_CAJAResult">
      <Column Name="IdCaja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoInicialCaja" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_BUSCA_HISTORIAL_CIERRE_CAJA" Method="SP_BUSCA_HISTORIAL_CIERRE_CAJA">
    <Parameter Name="IdHistorialCierreCaja" Parameter="idHistorialCierreCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCierreDesde" Parameter="fechaCierreDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCierreHasta" Parameter="fechaCierreHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_HISTORIAL_CIERRE_CAJAResult">
      <Column Name="IdHistirualCierreCaja" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CerradoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaCierre0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCierre" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="MontoAntesCerrar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoDespuesCierre" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ConceptoCierre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MANTENIMIENTO_HISTORIAL_CIERRE_CAJA" Method="SP_MANTENIMIENTO_HISTORIAL_CIERRE_CAJA">
    <Parameter Name="IdHistorialCierreCaja" Parameter="idHistorialCierreCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoAntesCerrar" Parameter="montoAntesCerrar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoDespuesCerrar" Parameter="montoDespuesCerrar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ConceptoCierre" Parameter="conceptoCierre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORIAL_CIERRE_CAJAResult">
      <Column Name="IdHistorialCierreCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCierre" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MontoAntesCerrar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoDespuesCerrar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ConceptoCierre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>