#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMarket.Data.Conexion.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSMarket")]
	public partial class BDConexionConfiguracionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionConfiguracionDataContext() : 
				base(global::DSMarket.Data.Properties.Settings.Default.DSMarketConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_BUSCA_LISTAS")]
		public ISingleResult<SP_BUSCA_LISTASResult> SP_BUSCA_LISTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreLista", DbType="VarChar(150)")] string nombreLista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerFiltro", DbType="VarChar(150)")] string primerFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoFiltro", DbType="VarChar(150)")] string segundoFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TerceFiltro", DbType="VarChar(150)")] string terceFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuartoFiltro", DbType="VarChar(150)")] string cuartoFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuintoFiltro", DbType="VarChar(150)")] string quintoFiltro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreLista, primerFiltro, segundoFiltro, terceFiltro, cuartoFiltro, quintoFiltro);
			return ((ISingleResult<SP_BUSCA_LISTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_SACAR_INFORMACION_EMPRESA")]
		public ISingleResult<SP_SACAR_INFORMACION_EMPRESAResult> SP_SACAR_INFORMACION_EMPRESA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_SACAR_INFORMACION_EMPRESAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_MODIFICAR_INFORMACION_EMPRESA")]
		public ISingleResult<SP_MODIFICAR_INFORMACION_EMPRESAResult> SP_MODIFICAR_INFORMACION_EMPRESA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInformacionEmpresa", DbType="Decimal(20,0)")] System.Nullable<decimal> idInformacionEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreEmpresa", DbType="VarChar(100)")] string nombreEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNC", DbType="VarChar(20)")] string rNC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email2", DbType="VarChar(50)")] string email2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Facebook", DbType="VarChar(50)")] string facebook, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Instagran", DbType="VarChar(50)")] string instagran, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefonos", DbType="VarChar(200)")] string telefonos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdLogoEmpresa", DbType="Int")] System.Nullable<int> idLogoEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInformacionEmpresa, nombreEmpresa, rNC, direccion, email, email2, facebook, instagran, telefonos, idLogoEmpresa, accion);
			return ((ISingleResult<SP_MODIFICAR_INFORMACION_EMPRESAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_GENERAR_COMPROBANTE_FISCAL")]
		public ISingleResult<SP_GENERAR_COMPROBANTE_FISCALResult> SP_GENERAR_COMPROBANTE_FISCAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobante);
			return ((ISingleResult<SP_GENERAR_COMPROBANTE_FISCALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_BUSCA_COMPROBANTES_FISCALES")]
		public ISingleResult<SP_BUSCA_COMPROBANTES_FISCALESResult> SP_BUSCA_COMPROBANTES_FISCALES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobanteFiscales", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobanteFiscales)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobanteFiscales);
			return ((ISingleResult<SP_BUSCA_COMPROBANTES_FISCALESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_MANTENIMIENTO_COMPROBANTE_FISCALES")]
		public ISingleResult<SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult> SP_MANTENIMIENTO_COMPROBANTE_FISCALES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Serie", DbType="VarChar(1)")] string serie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoComprobante", DbType="VarChar(2)")] string tipoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Secuencia", DbType="BigInt")] System.Nullable<long> secuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecuenciaInicial", DbType="BigInt")] System.Nullable<long> secuenciaInicial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecuenciaFinal", DbType="BigInt")] System.Nullable<long> secuenciaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Limite", DbType="BigInt")] System.Nullable<long> limite, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValidoHasta", DbType="VarChar(50)")] string validoHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PorDefecto", DbType="Bit")] System.Nullable<bool> porDefecto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Posiciones", DbType="BigInt")] System.Nullable<long> posiciones, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobante, descripcion, serie, tipoComprobante, secuencia, secuenciaInicial, secuenciaFinal, limite, estatus, validoHasta, porDefecto, posiciones, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_BUSCA_CONFIGURACION_GENERAL")]
		public ISingleResult<SP_BUSCA_CONFIGURACION_GENERALResult> SP_BUSCA_CONFIGURACION_GENERAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdConfiguracionGeneral", DbType="Int")] System.Nullable<int> idConfiguracionGeneral)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idConfiguracionGeneral);
			return ((ISingleResult<SP_BUSCA_CONFIGURACION_GENERALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_MANTENIMIENTO_CONFIGURACION_GENERAL")]
		public ISingleResult<SP_MANTENIMIENTO_CONFIGURACION_GENERALResult> SP_MANTENIMIENTO_CONFIGURACION_GENERAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdConfiguracionGeneral", DbType="Int")] System.Nullable<int> idConfiguracionGeneral, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idConfiguracionGeneral, descripcion, estatus, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_CONFIGURACION_GENERALResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_BUSCA_LISTASResult
	{
		
		private string _Descripcion;
		
		private string _PrimerValor;
		
		private string _SegundoValor;
		
		private string _TerceValor;
		
		public SP_BUSCA_LISTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerValor", DbType="VarChar(150)")]
		public string PrimerValor
		{
			get
			{
				return this._PrimerValor;
			}
			set
			{
				if ((this._PrimerValor != value))
				{
					this._PrimerValor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoValor", DbType="VarChar(150)")]
		public string SegundoValor
		{
			get
			{
				return this._SegundoValor;
			}
			set
			{
				if ((this._SegundoValor != value))
				{
					this._SegundoValor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerceValor", DbType="VarChar(150)")]
		public string TerceValor
		{
			get
			{
				return this._TerceValor;
			}
			set
			{
				if ((this._TerceValor != value))
				{
					this._TerceValor = value;
				}
			}
		}
	}
	
	public partial class SP_SACAR_INFORMACION_EMPRESAResult
	{
		
		private System.Nullable<decimal> _IdInformacionEmpresa;
		
		private string _NombreEmpresa;
		
		private string _RNC;
		
		private string _Direccion;
		
		private string _Email;
		
		private string _Email2;
		
		private string _Facebook;
		
		private string _Instagran;
		
		private string _Telefonos;
		
		private System.Nullable<int> _IdLogoEmpresa;
		
		private System.Data.Linq.Binary _LogoEmpresa;
		
		public SP_SACAR_INFORMACION_EMPRESAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInformacionEmpresa", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdInformacionEmpresa
		{
			get
			{
				return this._IdInformacionEmpresa;
			}
			set
			{
				if ((this._IdInformacionEmpresa != value))
				{
					this._IdInformacionEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmpresa", DbType="VarChar(100)")]
		public string NombreEmpresa
		{
			get
			{
				return this._NombreEmpresa;
			}
			set
			{
				if ((this._NombreEmpresa != value))
				{
					this._NombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNC", DbType="VarChar(20)")]
		public string RNC
		{
			get
			{
				return this._RNC;
			}
			set
			{
				if ((this._RNC != value))
				{
					this._RNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email2", DbType="VarChar(50)")]
		public string Email2
		{
			get
			{
				return this._Email2;
			}
			set
			{
				if ((this._Email2 != value))
				{
					this._Email2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook", DbType="VarChar(50)")]
		public string Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this._Facebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instagran", DbType="VarChar(50)")]
		public string Instagran
		{
			get
			{
				return this._Instagran;
			}
			set
			{
				if ((this._Instagran != value))
				{
					this._Instagran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(200)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLogoEmpresa", DbType="Int")]
		public System.Nullable<int> IdLogoEmpresa
		{
			get
			{
				return this._IdLogoEmpresa;
			}
			set
			{
				if ((this._IdLogoEmpresa != value))
				{
					this._IdLogoEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoEmpresa", DbType="Image")]
		public System.Data.Linq.Binary LogoEmpresa
		{
			get
			{
				return this._LogoEmpresa;
			}
			set
			{
				if ((this._LogoEmpresa != value))
				{
					this._LogoEmpresa = value;
				}
			}
		}
	}
	
	public partial class SP_MODIFICAR_INFORMACION_EMPRESAResult
	{
		
		private System.Nullable<decimal> _IdInformacionEmpresa;
		
		private string _NombreEmpresa;
		
		private string _RNC;
		
		private string _Direccion;
		
		private string _Email;
		
		private string _Email2;
		
		private string _Facebook;
		
		private string _Instagran;
		
		private string _Telefonos;
		
		private System.Nullable<int> _IdLogoEmpresa;
		
		public SP_MODIFICAR_INFORMACION_EMPRESAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInformacionEmpresa", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdInformacionEmpresa
		{
			get
			{
				return this._IdInformacionEmpresa;
			}
			set
			{
				if ((this._IdInformacionEmpresa != value))
				{
					this._IdInformacionEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmpresa", DbType="VarChar(100)")]
		public string NombreEmpresa
		{
			get
			{
				return this._NombreEmpresa;
			}
			set
			{
				if ((this._NombreEmpresa != value))
				{
					this._NombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNC", DbType="VarChar(20)")]
		public string RNC
		{
			get
			{
				return this._RNC;
			}
			set
			{
				if ((this._RNC != value))
				{
					this._RNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email2", DbType="VarChar(50)")]
		public string Email2
		{
			get
			{
				return this._Email2;
			}
			set
			{
				if ((this._Email2 != value))
				{
					this._Email2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook", DbType="VarChar(50)")]
		public string Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this._Facebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instagran", DbType="VarChar(50)")]
		public string Instagran
		{
			get
			{
				return this._Instagran;
			}
			set
			{
				if ((this._Instagran != value))
				{
					this._Instagran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(200)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLogoEmpresa", DbType="Int")]
		public System.Nullable<int> IdLogoEmpresa
		{
			get
			{
				return this._IdLogoEmpresa;
			}
			set
			{
				if ((this._IdLogoEmpresa != value))
				{
					this._IdLogoEmpresa = value;
				}
			}
		}
	}
	
	public partial class SP_GENERAR_COMPROBANTE_FISCALResult
	{
		
		private string _TipoComprobante;
		
		private string _Comprobante;
		
		public SP_GENERAR_COMPROBANTE_FISCALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(100)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_COMPROBANTES_FISCALESResult
	{
		
		private decimal _IdComprobante;
		
		private string _Comprobante;
		
		private string _Serie;
		
		private string _TipoComprobante;
		
		private System.Nullable<decimal> _Secuencia;
		
		private System.Nullable<decimal> _SecuenciaInicial;
		
		private System.Nullable<decimal> _SecuenciaFinal;
		
		private System.Nullable<decimal> _Limite;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private string _ValidoHasta;
		
		private System.Nullable<bool> _PorDefecto0;
		
		private string _PorDefecto;
		
		private System.Nullable<decimal> _Posiciones;
		
		public SP_BUSCA_COMPROBANTES_FISCALESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(100)")]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="VarChar(1)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this._Serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(2)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secuencia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Secuencia
		{
			get
			{
				return this._Secuencia;
			}
			set
			{
				if ((this._Secuencia != value))
				{
					this._Secuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaInicial", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> SecuenciaInicial
		{
			get
			{
				return this._SecuenciaInicial;
			}
			set
			{
				if ((this._SecuenciaInicial != value))
				{
					this._SecuenciaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaFinal", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> SecuenciaFinal
		{
			get
			{
				return this._SecuenciaFinal;
			}
			set
			{
				if ((this._SecuenciaFinal != value))
				{
					this._SecuenciaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Limite", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Limite
		{
			get
			{
				return this._Limite;
			}
			set
			{
				if ((this._Limite != value))
				{
					this._Limite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8)")]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidoHasta", DbType="VarChar(50)")]
		public string ValidoHasta
		{
			get
			{
				return this._ValidoHasta;
			}
			set
			{
				if ((this._ValidoHasta != value))
				{
					this._ValidoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto0", DbType="Bit")]
		public System.Nullable<bool> PorDefecto0
		{
			get
			{
				return this._PorDefecto0;
			}
			set
			{
				if ((this._PorDefecto0 != value))
				{
					this._PorDefecto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto", DbType="VarChar(2)")]
		public string PorDefecto
		{
			get
			{
				return this._PorDefecto;
			}
			set
			{
				if ((this._PorDefecto != value))
				{
					this._PorDefecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posiciones", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> Posiciones
		{
			get
			{
				return this._Posiciones;
			}
			set
			{
				if ((this._Posiciones != value))
				{
					this._Posiciones = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult
	{
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Descripcion;
		
		private string _Serie;
		
		private string _TipoComprobante;
		
		private System.Nullable<long> _Secuencia;
		
		private System.Nullable<long> _SecuenciaInicial;
		
		private System.Nullable<long> _SecuenciaFinal;
		
		private System.Nullable<long> _Limite;
		
		private System.Nullable<bool> _Estatus;
		
		private string _ValidoHasta;
		
		private System.Nullable<bool> _PorDefecto;
		
		private System.Nullable<long> _Posiciones;
		
		public SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="VarChar(1)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this._Serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(2)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secuencia", DbType="BigInt")]
		public System.Nullable<long> Secuencia
		{
			get
			{
				return this._Secuencia;
			}
			set
			{
				if ((this._Secuencia != value))
				{
					this._Secuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaInicial", DbType="BigInt")]
		public System.Nullable<long> SecuenciaInicial
		{
			get
			{
				return this._SecuenciaInicial;
			}
			set
			{
				if ((this._SecuenciaInicial != value))
				{
					this._SecuenciaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaFinal", DbType="BigInt")]
		public System.Nullable<long> SecuenciaFinal
		{
			get
			{
				return this._SecuenciaFinal;
			}
			set
			{
				if ((this._SecuenciaFinal != value))
				{
					this._SecuenciaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Limite", DbType="BigInt")]
		public System.Nullable<long> Limite
		{
			get
			{
				return this._Limite;
			}
			set
			{
				if ((this._Limite != value))
				{
					this._Limite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidoHasta", DbType="VarChar(50)")]
		public string ValidoHasta
		{
			get
			{
				return this._ValidoHasta;
			}
			set
			{
				if ((this._ValidoHasta != value))
				{
					this._ValidoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto", DbType="Bit")]
		public System.Nullable<bool> PorDefecto
		{
			get
			{
				return this._PorDefecto;
			}
			set
			{
				if ((this._PorDefecto != value))
				{
					this._PorDefecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posiciones", DbType="BigInt")]
		public System.Nullable<long> Posiciones
		{
			get
			{
				return this._Posiciones;
			}
			set
			{
				if ((this._Posiciones != value))
				{
					this._Posiciones = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_CONFIGURACION_GENERALResult
	{
		
		private int _IdConfiguracionGeneral;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<int> _CantidadActivos;
		
		private System.Nullable<int> _CantidadInactivos;
		
		public SP_BUSCA_CONFIGURACION_GENERALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConfiguracionGeneral", DbType="Int NOT NULL")]
		public int IdConfiguracionGeneral
		{
			get
			{
				return this._IdConfiguracionGeneral;
			}
			set
			{
				if ((this._IdConfiguracionGeneral != value))
				{
					this._IdConfiguracionGeneral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadActivos", DbType="Int")]
		public System.Nullable<int> CantidadActivos
		{
			get
			{
				return this._CantidadActivos;
			}
			set
			{
				if ((this._CantidadActivos != value))
				{
					this._CantidadActivos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadInactivos", DbType="Int")]
		public System.Nullable<int> CantidadInactivos
		{
			get
			{
				return this._CantidadInactivos;
			}
			set
			{
				if ((this._CantidadInactivos != value))
				{
					this._CantidadInactivos = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_CONFIGURACION_GENERALResult
	{
		
		private System.Nullable<int> _IdConfiguracionGeneral;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		public SP_MANTENIMIENTO_CONFIGURACION_GENERALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConfiguracionGeneral", DbType="Int")]
		public System.Nullable<int> IdConfiguracionGeneral
		{
			get
			{
				return this._IdConfiguracionGeneral;
			}
			set
			{
				if ((this._IdConfiguracionGeneral != value))
				{
					this._IdConfiguracionGeneral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
