#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMarket.Data.Conexion.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSMarket")]
	public partial class BDConexionEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionEmpresaDataContext() : 
				base(global::DSMarket.Data.Properties.Settings.Default.DSMarketConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_CLIENTES")]
		public ISingleResult<SP_MANTENIMIENTO_CLIENTESResult> SP_MANTENIMIENTO_CLIENTES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Decimal(20,0)")] System.Nullable<decimal> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoIdentificacion", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoIdentificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNC", DbType="VarChar(100)")] string rNC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comentario", DbType="VarChar(8000)")] string comentario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoCredito", DbType="Decimal(20,2)")] System.Nullable<decimal> montoCredito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnvioEmail", DbType="Bit")] System.Nullable<bool> envioEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, idComprobante, nombre, telefono, idTipoIdentificacion, rNC, direccion, email, comentario, estatus, idUsuario, montoCredito, envioEmail, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_CLIENTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_CLIENTES")]
		public ISingleResult<SP_BUSCA_CLIENTESResult> SP_BUSCA_CLIENTES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Decimal(20,0)")] System.Nullable<decimal> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNC", DbType="VarChar(20)")] string rNC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnvioEmail", DbType="Bit")] System.Nullable<bool> envioEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, idComprobante, nombre, rNC, estatus, envioEmail, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_CLIENTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_COMPRAS_SUPLIDORES")]
		public ISingleResult<SP_MANTENIMIENTO_COMPRAS_SUPLIDORESResult> SP_MANTENIMIENTO_COMPRAS_SUPLIDORES(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCompraSuplidor", DbType="Decimal(20,0)")] System.Nullable<decimal> idCompraSuplidor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoSuplidor", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoSuplidor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSuplidor", DbType="Decimal(20,0)")] System.Nullable<decimal> idSuplidor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNCCedula", DbType="VarChar(100)")] string rNCCedula, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoIdentificacion", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoIdentificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoBienesServicios", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoBienesServicios, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCF", DbType="VarChar(100)")] string nCF, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCFModificado", DbType="VarChar(100)")] string nCFModificado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaComprobante", DbType="Date")] System.Nullable<System.DateTime> fechaComprobante, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaPago", DbType="Date")] System.Nullable<System.DateTime> fechaPago, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoFacturadoServicios", DbType="Decimal(20,2)")] System.Nullable<decimal> montoFacturadoServicios, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoFacturadoBienes", DbType="Decimal(20,2)")] System.Nullable<decimal> montoFacturadoBienes, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalMontoFacturado", DbType="Decimal(20,2)")] System.Nullable<decimal> totalMontoFacturado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ITBISFacturado", DbType="Decimal(20,2)")] System.Nullable<decimal> iTBISFacturado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ITBISRetenido", DbType="Decimal(20,2)")] System.Nullable<decimal> iTBISRetenido, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ITBISSujetoProporcionalidad", DbType="Decimal(20,2)")] System.Nullable<decimal> iTBISSujetoProporcionalidad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ITBISLlevadoCosto", DbType="Decimal(20,2)")] System.Nullable<decimal> iTBISLlevadoCosto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ITBISPorAdelantar", DbType="Decimal(20,2)")] System.Nullable<decimal> iTBISPorAdelantar, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ITBISPercibidoCompras", DbType="Decimal(20,2)")] System.Nullable<decimal> iTBISPercibidoCompras, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoRetencionISR", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoRetencionISR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoRetencionRenta", DbType="Decimal(20,2)")] System.Nullable<decimal> montoRetencionRenta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISRPercibidoCompras", DbType="Decimal(20,2)")] System.Nullable<decimal> iSRPercibidoCompras, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImpuestoSelectivoConsumo", DbType="Decimal(20,2)")] System.Nullable<decimal> impuestoSelectivoConsumo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OtrosImpuestosTasa", DbType="Decimal(20,2)")] System.Nullable<decimal> otrosImpuestosTasa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoPropinaLegal", DbType="Decimal(20,2)")] System.Nullable<decimal> montoPropinaLegal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFormaPago", DbType="Decimal(20,0)")] System.Nullable<decimal> idFormaPago, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioAdiciona", DbType="Decimal(20,0)")] System.Nullable<decimal> usuarioAdiciona, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCreado", DbType="Date")] System.Nullable<System.DateTime> fechaCreado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCompraSuplidor, idTipoSuplidor, idSuplidor, rNCCedula, idTipoIdentificacion, idTipoBienesServicios, nCF, nCFModificado, fechaComprobante, fechaPago, montoFacturadoServicios, montoFacturadoBienes, totalMontoFacturado, iTBISFacturado, iTBISRetenido, iTBISSujetoProporcionalidad, iTBISLlevadoCosto, iTBISPorAdelantar, iTBISPercibidoCompras, idTipoRetencionISR, montoRetencionRenta, iSRPercibidoCompras, impuestoSelectivoConsumo, otrosImpuestosTasa, montoPropinaLegal, idFormaPago, usuarioAdiciona, fechaCreado, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_COMPRAS_SUPLIDORESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_REGISTROS_COMPRA_SUPLIDORES")]
		public ISingleResult<SP_BUSCA_REGISTROS_COMPRA_SUPLIDORESResult> SP_BUSCA_REGISTROS_COMPRA_SUPLIDORES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCompraSuplidor", DbType="Decimal(20,0)")] System.Nullable<decimal> idCompraSuplidor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoSuplidor", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoSuplidor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSuplidor", DbType="Decimal(20,0)")] System.Nullable<decimal> idSuplidor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNCCedula", DbType="VarChar(100)")] string rNCCedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCreadoDesde", DbType="Date")] System.Nullable<System.DateTime> fechaCreadoDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCreadoHasta", DbType="Date")] System.Nullable<System.DateTime> fechaCreadoHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCompraSuplidor, idTipoSuplidor, idSuplidor, rNCCedula, fechaCreadoDesde, fechaCreadoHasta, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_REGISTROS_COMPRA_SUPLIDORESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_DEPARTAMENTOS")]
		public ISingleResult<SP_MANTENIMIENTO_DEPARTAMENTOSResult> SP_MANTENIMIENTO_DEPARTAMENTOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartamento", DbType="Decimal(20,0)")] System.Nullable<decimal> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_DEPARTAMENTOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_DEPARTAMENTOS")]
		public ISingleResult<SP_BUSCA_DEPARTAMENTOSResult> SP_BUSCA_DEPARTAMENTOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartamento", DbType="Decimal(20,0)")] System.Nullable<decimal> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_DEPARTAMENTOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_CARGOS")]
		public ISingleResult<SP_BUSCA_CARGOSResult> SP_BUSCA_CARGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCargo", DbType="Decimal(20,0)")] System.Nullable<decimal> idCargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartamento", DbType="Decimal(20,0)")] System.Nullable<decimal> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistro", DbType="Int")] System.Nullable<int> numeroRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCargo, idDepartamento, descripcion, numeroPagina, numeroRegistro);
			return ((ISingleResult<SP_BUSCA_CARGOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_CARGOS")]
		public ISingleResult<SP_MANTENIMIENTO_CARGOSResult> SP_MANTENIMIENTO_CARGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCargo", DbType="Decimal(20,0)")] System.Nullable<decimal> idCargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartamento", DbType="Decimal(20,0)")] System.Nullable<decimal> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCargo, idDepartamento, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_CARGOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_TIPO_EMPLEADO")]
		public ISingleResult<SP_BUSCA_TIPO_EMPLEADOResult> SP_BUSCA_TIPO_EMPLEADO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpleado", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoEmpleado, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_TIPO_EMPLEADOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_TIPO_EMPLEADO")]
		public ISingleResult<SP_MANTENIMIENTO_TIPO_EMPLEADOResult> SP_MANTENIMIENTO_TIPO_EMPLEADO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpleado", DbType="Decimal(20,2)")] System.Nullable<decimal> idTipoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Idusuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idusuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoEmpleado, descripcion, estatus, idusuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_TIPO_EMPLEADOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_TIPO_NOMINA")]
		public ISingleResult<SP_BUSCA_TIPO_NOMINAResult> SP_BUSCA_TIPO_NOMINA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoNomina", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoNomina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoNomina, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_TIPO_NOMINAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_TIPO_NOMINA")]
		public ISingleResult<SP_MANTENIMIENTO_TIPO_NOMINAResult> SP_MANTENIMIENTO_TIPO_NOMINA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoNomina", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoNomina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoNomina, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_TIPO_NOMINAResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_MANTENIMIENTO_CLIENTESResult
	{
		
		private System.Nullable<decimal> _IdCliente;
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Nombre;
		
		private string _Telefono;
		
		private System.Nullable<decimal> _IdTipoIdentificacion;
		
		private string _RNC;
		
		private string _Direccion;
		
		private string _Email;
		
		private string _Comentario;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private System.Nullable<decimal> _MontoCredito;
		
		private System.Nullable<bool> _EnvioEmail;
		
		public SP_MANTENIMIENTO_CLIENTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNC", DbType="VarChar(100)")]
		public string RNC
		{
			get
			{
				return this._RNC;
			}
			set
			{
				if ((this._RNC != value))
				{
					this._RNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(8000)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoCredito
		{
			get
			{
				return this._MontoCredito;
			}
			set
			{
				if ((this._MontoCredito != value))
				{
					this._MontoCredito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvioEmail", DbType="Bit")]
		public System.Nullable<bool> EnvioEmail
		{
			get
			{
				return this._EnvioEmail;
			}
			set
			{
				if ((this._EnvioEmail != value))
				{
					this._EnvioEmail = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_CLIENTESResult
	{
		
		private decimal _IdCliente;
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Comprobante;
		
		private string _Nombre;
		
		private string _Telefono;
		
		private System.Nullable<decimal> _IdTipoIdentificacion;
		
		private string _TipoIdentificacion;
		
		private string _RNC;
		
		private string _Direccion;
		
		private string _Email;
		
		private string _Comentario;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<bool> _EnvioEmail0;
		
		private string _EnvioEmail;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private string _FechaCreado;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _FechaModificado;
		
		private System.Nullable<decimal> _MontoCredito;
		
		private System.Nullable<int> _CantidadClientes;
		
		public SP_BUSCA_CLIENTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(100)")]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificacion", DbType="VarChar(100)")]
		public string TipoIdentificacion
		{
			get
			{
				return this._TipoIdentificacion;
			}
			set
			{
				if ((this._TipoIdentificacion != value))
				{
					this._TipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNC", DbType="VarChar(100)")]
		public string RNC
		{
			get
			{
				return this._RNC;
			}
			set
			{
				if ((this._RNC != value))
				{
					this._RNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(8000)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvioEmail0", DbType="Bit")]
		public System.Nullable<bool> EnvioEmail0
		{
			get
			{
				return this._EnvioEmail0;
			}
			set
			{
				if ((this._EnvioEmail0 != value))
				{
					this._EnvioEmail0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvioEmail", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string EnvioEmail
		{
			get
			{
				return this._EnvioEmail;
			}
			set
			{
				if ((this._EnvioEmail != value))
				{
					this._EnvioEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="NVarChar(4000)")]
		public string FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(100)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificado", DbType="NVarChar(4000)")]
		public string FechaModificado
		{
			get
			{
				return this._FechaModificado;
			}
			set
			{
				if ((this._FechaModificado != value))
				{
					this._FechaModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoCredito
		{
			get
			{
				return this._MontoCredito;
			}
			set
			{
				if ((this._MontoCredito != value))
				{
					this._MontoCredito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadClientes", DbType="Int")]
		public System.Nullable<int> CantidadClientes
		{
			get
			{
				return this._CantidadClientes;
			}
			set
			{
				if ((this._CantidadClientes != value))
				{
					this._CantidadClientes = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_COMPRAS_SUPLIDORESResult
	{
		
		private System.Nullable<decimal> _IdCompraSuplidor;
		
		private System.Nullable<decimal> _IdTipoSuplidor;
		
		private System.Nullable<decimal> _IdSuplidor;
		
		private string _RNCCedula;
		
		private System.Nullable<decimal> _IdTipoIdentificacion;
		
		private System.Nullable<decimal> _IdTipoBienesServicios;
		
		private string _NCF;
		
		private string _NCFModificado;
		
		private System.Nullable<System.DateTime> _FechaComprobante;
		
		private System.Nullable<System.DateTime> _FechaPago;
		
		private System.Nullable<decimal> _MontoFacturadoServicios;
		
		private System.Nullable<decimal> _MontoFacturadoBienes;
		
		private System.Nullable<decimal> _TotalMontoFacturado;
		
		private System.Nullable<decimal> _ITBISFacturado;
		
		private System.Nullable<decimal> _ITBISRetenido;
		
		private System.Nullable<decimal> _ITBISSujetoProporcionalidad;
		
		private System.Nullable<decimal> _ITBISLlevadoCosto;
		
		private System.Nullable<decimal> _ITBISPorAdelantar;
		
		private System.Nullable<decimal> _ITBISPercibidoCompras;
		
		private System.Nullable<decimal> _IdTipoRetencionISR;
		
		private System.Nullable<decimal> _MontoRetencionRenta;
		
		private System.Nullable<decimal> _ISRPercibidoCompras;
		
		private System.Nullable<decimal> _ImpuestoSelectivoConsumo;
		
		private System.Nullable<decimal> _OtrosImpuestosTasa;
		
		private System.Nullable<decimal> _MontoPropinaLegal;
		
		private System.Nullable<decimal> _IdFormaPago;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaCreado;
		
		public SP_MANTENIMIENTO_COMPRAS_SUPLIDORESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCompraSuplidor", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCompraSuplidor
		{
			get
			{
				return this._IdCompraSuplidor;
			}
			set
			{
				if ((this._IdCompraSuplidor != value))
				{
					this._IdCompraSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoSuplidor", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoSuplidor
		{
			get
			{
				return this._IdTipoSuplidor;
			}
			set
			{
				if ((this._IdTipoSuplidor != value))
				{
					this._IdTipoSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSuplidor", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdSuplidor
		{
			get
			{
				return this._IdSuplidor;
			}
			set
			{
				if ((this._IdSuplidor != value))
				{
					this._IdSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNCCedula", DbType="VarChar(100)")]
		public string RNCCedula
		{
			get
			{
				return this._RNCCedula;
			}
			set
			{
				if ((this._RNCCedula != value))
				{
					this._RNCCedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoBienesServicios", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoBienesServicios
		{
			get
			{
				return this._IdTipoBienesServicios;
			}
			set
			{
				if ((this._IdTipoBienesServicios != value))
				{
					this._IdTipoBienesServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCF", DbType="VarChar(100)")]
		public string NCF
		{
			get
			{
				return this._NCF;
			}
			set
			{
				if ((this._NCF != value))
				{
					this._NCF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCFModificado", DbType="VarChar(100)")]
		public string NCFModificado
		{
			get
			{
				return this._NCFModificado;
			}
			set
			{
				if ((this._NCFModificado != value))
				{
					this._NCFModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaComprobante", DbType="Date")]
		public System.Nullable<System.DateTime> FechaComprobante
		{
			get
			{
				return this._FechaComprobante;
			}
			set
			{
				if ((this._FechaComprobante != value))
				{
					this._FechaComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPago", DbType="Date")]
		public System.Nullable<System.DateTime> FechaPago
		{
			get
			{
				return this._FechaPago;
			}
			set
			{
				if ((this._FechaPago != value))
				{
					this._FechaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFacturadoServicios", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFacturadoServicios
		{
			get
			{
				return this._MontoFacturadoServicios;
			}
			set
			{
				if ((this._MontoFacturadoServicios != value))
				{
					this._MontoFacturadoServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFacturadoBienes", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFacturadoBienes
		{
			get
			{
				return this._MontoFacturadoBienes;
			}
			set
			{
				if ((this._MontoFacturadoBienes != value))
				{
					this._MontoFacturadoBienes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMontoFacturado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalMontoFacturado
		{
			get
			{
				return this._TotalMontoFacturado;
			}
			set
			{
				if ((this._TotalMontoFacturado != value))
				{
					this._TotalMontoFacturado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISFacturado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISFacturado
		{
			get
			{
				return this._ITBISFacturado;
			}
			set
			{
				if ((this._ITBISFacturado != value))
				{
					this._ITBISFacturado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISRetenido", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISRetenido
		{
			get
			{
				return this._ITBISRetenido;
			}
			set
			{
				if ((this._ITBISRetenido != value))
				{
					this._ITBISRetenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISSujetoProporcionalidad", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISSujetoProporcionalidad
		{
			get
			{
				return this._ITBISSujetoProporcionalidad;
			}
			set
			{
				if ((this._ITBISSujetoProporcionalidad != value))
				{
					this._ITBISSujetoProporcionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISLlevadoCosto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISLlevadoCosto
		{
			get
			{
				return this._ITBISLlevadoCosto;
			}
			set
			{
				if ((this._ITBISLlevadoCosto != value))
				{
					this._ITBISLlevadoCosto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISPorAdelantar", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISPorAdelantar
		{
			get
			{
				return this._ITBISPorAdelantar;
			}
			set
			{
				if ((this._ITBISPorAdelantar != value))
				{
					this._ITBISPorAdelantar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISPercibidoCompras", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISPercibidoCompras
		{
			get
			{
				return this._ITBISPercibidoCompras;
			}
			set
			{
				if ((this._ITBISPercibidoCompras != value))
				{
					this._ITBISPercibidoCompras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoRetencionISR", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoRetencionISR
		{
			get
			{
				return this._IdTipoRetencionISR;
			}
			set
			{
				if ((this._IdTipoRetencionISR != value))
				{
					this._IdTipoRetencionISR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoRetencionRenta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoRetencionRenta
		{
			get
			{
				return this._MontoRetencionRenta;
			}
			set
			{
				if ((this._MontoRetencionRenta != value))
				{
					this._MontoRetencionRenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISRPercibidoCompras", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ISRPercibidoCompras
		{
			get
			{
				return this._ISRPercibidoCompras;
			}
			set
			{
				if ((this._ISRPercibidoCompras != value))
				{
					this._ISRPercibidoCompras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpuestoSelectivoConsumo", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ImpuestoSelectivoConsumo
		{
			get
			{
				return this._ImpuestoSelectivoConsumo;
			}
			set
			{
				if ((this._ImpuestoSelectivoConsumo != value))
				{
					this._ImpuestoSelectivoConsumo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtrosImpuestosTasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> OtrosImpuestosTasa
		{
			get
			{
				return this._OtrosImpuestosTasa;
			}
			set
			{
				if ((this._OtrosImpuestosTasa != value))
				{
					this._OtrosImpuestosTasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPropinaLegal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPropinaLegal
		{
			get
			{
				return this._MontoPropinaLegal;
			}
			set
			{
				if ((this._MontoPropinaLegal != value))
				{
					this._MontoPropinaLegal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFormaPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdFormaPago
		{
			get
			{
				return this._IdFormaPago;
			}
			set
			{
				if ((this._IdFormaPago != value))
				{
					this._IdFormaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_REGISTROS_COMPRA_SUPLIDORESResult
	{
		
		private decimal _IdCompraSuplidor;
		
		private System.Nullable<decimal> _IdTipoSuplidor;
		
		private string _TipoSuplidor;
		
		private System.Nullable<decimal> _IdSuplidor;
		
		private string _Suplidor;
		
		private string _RNCCedula;
		
		private System.Nullable<decimal> _IdTipoIdentificacion;
		
		private string _TipoIdentificacion;
		
		private System.Nullable<decimal> _IdTipoBienesServicios;
		
		private string _TipoBienesServicios;
		
		private string _CodigoTipoBienesServicio;
		
		private string _NCF;
		
		private string _NCFModificado;
		
		private System.Nullable<System.DateTime> _FechaComprobante0;
		
		private string _FechaComprobante;
		
		private System.Nullable<System.DateTime> _FechaPago0;
		
		private string _FechaPago;
		
		private System.Nullable<decimal> _MontoFacturadoServicios;
		
		private System.Nullable<decimal> _MontoFacturadoBienes;
		
		private System.Nullable<decimal> _TotalMontoFacturado;
		
		private System.Nullable<decimal> _ITBISFacturado;
		
		private System.Nullable<decimal> _ITBISRetenido;
		
		private System.Nullable<decimal> _ITBISSujetoProporcionalidad;
		
		private System.Nullable<decimal> _ITBISLlevadoCosto;
		
		private System.Nullable<decimal> _ITBISPorAdelantar;
		
		private System.Nullable<decimal> _ITBISPercibidoCompras;
		
		private System.Nullable<decimal> _IdTipoRetencionISR;
		
		private string _TipoRetencionISR;
		
		private string _CodigoTipoRetencionISR;
		
		private System.Nullable<decimal> _MontoRetencionRenta;
		
		private System.Nullable<decimal> _ISRPercibidoCompras;
		
		private System.Nullable<decimal> _ImpuestoSelectivoConsumo;
		
		private System.Nullable<decimal> _OtrosImpuestosTasa;
		
		private System.Nullable<decimal> _MontoPropinaLegal;
		
		private System.Nullable<decimal> _IdFormaPago;
		
		private string _FormaPago;
		
		private string _CodigoTipoPago;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaCreado0;
		
		private string _FechaCreado;
		
		private System.Nullable<int> _CantidadRegistros;
		
		public SP_BUSCA_REGISTROS_COMPRA_SUPLIDORESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCompraSuplidor", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdCompraSuplidor
		{
			get
			{
				return this._IdCompraSuplidor;
			}
			set
			{
				if ((this._IdCompraSuplidor != value))
				{
					this._IdCompraSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoSuplidor", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoSuplidor
		{
			get
			{
				return this._IdTipoSuplidor;
			}
			set
			{
				if ((this._IdTipoSuplidor != value))
				{
					this._IdTipoSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoSuplidor", DbType="VarChar(100)")]
		public string TipoSuplidor
		{
			get
			{
				return this._TipoSuplidor;
			}
			set
			{
				if ((this._TipoSuplidor != value))
				{
					this._TipoSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSuplidor", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdSuplidor
		{
			get
			{
				return this._IdSuplidor;
			}
			set
			{
				if ((this._IdSuplidor != value))
				{
					this._IdSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suplidor", DbType="VarChar(100)")]
		public string Suplidor
		{
			get
			{
				return this._Suplidor;
			}
			set
			{
				if ((this._Suplidor != value))
				{
					this._Suplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNCCedula", DbType="VarChar(100)")]
		public string RNCCedula
		{
			get
			{
				return this._RNCCedula;
			}
			set
			{
				if ((this._RNCCedula != value))
				{
					this._RNCCedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificacion", DbType="VarChar(100)")]
		public string TipoIdentificacion
		{
			get
			{
				return this._TipoIdentificacion;
			}
			set
			{
				if ((this._TipoIdentificacion != value))
				{
					this._TipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoBienesServicios", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoBienesServicios
		{
			get
			{
				return this._IdTipoBienesServicios;
			}
			set
			{
				if ((this._IdTipoBienesServicios != value))
				{
					this._IdTipoBienesServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoBienesServicios", DbType="VarChar(100)")]
		public string TipoBienesServicios
		{
			get
			{
				return this._TipoBienesServicios;
			}
			set
			{
				if ((this._TipoBienesServicios != value))
				{
					this._TipoBienesServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoBienesServicio", DbType="VarChar(2)")]
		public string CodigoTipoBienesServicio
		{
			get
			{
				return this._CodigoTipoBienesServicio;
			}
			set
			{
				if ((this._CodigoTipoBienesServicio != value))
				{
					this._CodigoTipoBienesServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCF", DbType="VarChar(100)")]
		public string NCF
		{
			get
			{
				return this._NCF;
			}
			set
			{
				if ((this._NCF != value))
				{
					this._NCF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCFModificado", DbType="VarChar(100)")]
		public string NCFModificado
		{
			get
			{
				return this._NCFModificado;
			}
			set
			{
				if ((this._NCFModificado != value))
				{
					this._NCFModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaComprobante0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaComprobante0
		{
			get
			{
				return this._FechaComprobante0;
			}
			set
			{
				if ((this._FechaComprobante0 != value))
				{
					this._FechaComprobante0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaComprobante", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string FechaComprobante
		{
			get
			{
				return this._FechaComprobante;
			}
			set
			{
				if ((this._FechaComprobante != value))
				{
					this._FechaComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPago0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaPago0
		{
			get
			{
				return this._FechaPago0;
			}
			set
			{
				if ((this._FechaPago0 != value))
				{
					this._FechaPago0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPago", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string FechaPago
		{
			get
			{
				return this._FechaPago;
			}
			set
			{
				if ((this._FechaPago != value))
				{
					this._FechaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFacturadoServicios", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFacturadoServicios
		{
			get
			{
				return this._MontoFacturadoServicios;
			}
			set
			{
				if ((this._MontoFacturadoServicios != value))
				{
					this._MontoFacturadoServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFacturadoBienes", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFacturadoBienes
		{
			get
			{
				return this._MontoFacturadoBienes;
			}
			set
			{
				if ((this._MontoFacturadoBienes != value))
				{
					this._MontoFacturadoBienes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMontoFacturado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TotalMontoFacturado
		{
			get
			{
				return this._TotalMontoFacturado;
			}
			set
			{
				if ((this._TotalMontoFacturado != value))
				{
					this._TotalMontoFacturado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISFacturado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISFacturado
		{
			get
			{
				return this._ITBISFacturado;
			}
			set
			{
				if ((this._ITBISFacturado != value))
				{
					this._ITBISFacturado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISRetenido", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISRetenido
		{
			get
			{
				return this._ITBISRetenido;
			}
			set
			{
				if ((this._ITBISRetenido != value))
				{
					this._ITBISRetenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISSujetoProporcionalidad", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISSujetoProporcionalidad
		{
			get
			{
				return this._ITBISSujetoProporcionalidad;
			}
			set
			{
				if ((this._ITBISSujetoProporcionalidad != value))
				{
					this._ITBISSujetoProporcionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISLlevadoCosto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISLlevadoCosto
		{
			get
			{
				return this._ITBISLlevadoCosto;
			}
			set
			{
				if ((this._ITBISLlevadoCosto != value))
				{
					this._ITBISLlevadoCosto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISPorAdelantar", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISPorAdelantar
		{
			get
			{
				return this._ITBISPorAdelantar;
			}
			set
			{
				if ((this._ITBISPorAdelantar != value))
				{
					this._ITBISPorAdelantar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITBISPercibidoCompras", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ITBISPercibidoCompras
		{
			get
			{
				return this._ITBISPercibidoCompras;
			}
			set
			{
				if ((this._ITBISPercibidoCompras != value))
				{
					this._ITBISPercibidoCompras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoRetencionISR", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoRetencionISR
		{
			get
			{
				return this._IdTipoRetencionISR;
			}
			set
			{
				if ((this._IdTipoRetencionISR != value))
				{
					this._IdTipoRetencionISR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRetencionISR", DbType="VarChar(100)")]
		public string TipoRetencionISR
		{
			get
			{
				return this._TipoRetencionISR;
			}
			set
			{
				if ((this._TipoRetencionISR != value))
				{
					this._TipoRetencionISR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoRetencionISR", DbType="VarChar(2)")]
		public string CodigoTipoRetencionISR
		{
			get
			{
				return this._CodigoTipoRetencionISR;
			}
			set
			{
				if ((this._CodigoTipoRetencionISR != value))
				{
					this._CodigoTipoRetencionISR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoRetencionRenta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoRetencionRenta
		{
			get
			{
				return this._MontoRetencionRenta;
			}
			set
			{
				if ((this._MontoRetencionRenta != value))
				{
					this._MontoRetencionRenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISRPercibidoCompras", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ISRPercibidoCompras
		{
			get
			{
				return this._ISRPercibidoCompras;
			}
			set
			{
				if ((this._ISRPercibidoCompras != value))
				{
					this._ISRPercibidoCompras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpuestoSelectivoConsumo", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ImpuestoSelectivoConsumo
		{
			get
			{
				return this._ImpuestoSelectivoConsumo;
			}
			set
			{
				if ((this._ImpuestoSelectivoConsumo != value))
				{
					this._ImpuestoSelectivoConsumo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtrosImpuestosTasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> OtrosImpuestosTasa
		{
			get
			{
				return this._OtrosImpuestosTasa;
			}
			set
			{
				if ((this._OtrosImpuestosTasa != value))
				{
					this._OtrosImpuestosTasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPropinaLegal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPropinaLegal
		{
			get
			{
				return this._MontoPropinaLegal;
			}
			set
			{
				if ((this._MontoPropinaLegal != value))
				{
					this._MontoPropinaLegal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFormaPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdFormaPago
		{
			get
			{
				return this._IdFormaPago;
			}
			set
			{
				if ((this._IdFormaPago != value))
				{
					this._IdFormaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormaPago", DbType="VarChar(100)")]
		public string FormaPago
		{
			get
			{
				return this._FormaPago;
			}
			set
			{
				if ((this._FormaPago != value))
				{
					this._FormaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoPago", DbType="VarChar(2)")]
		public string CodigoTipoPago
		{
			get
			{
				return this._CodigoTipoPago;
			}
			set
			{
				if ((this._CodigoTipoPago != value))
				{
					this._CodigoTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCreado0
		{
			get
			{
				return this._FechaCreado0;
			}
			set
			{
				if ((this._FechaCreado0 != value))
				{
					this._FechaCreado0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="NVarChar(4000)")]
		public string FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadRegistros", DbType="Int")]
		public System.Nullable<int> CantidadRegistros
		{
			get
			{
				return this._CantidadRegistros;
			}
			set
			{
				if ((this._CantidadRegistros != value))
				{
					this._CantidadRegistros = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_DEPARTAMENTOSResult
	{
		
		private System.Nullable<decimal> _IdDepartamento;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_DEPARTAMENTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this._IdDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_DEPARTAMENTOSResult
	{
		
		private decimal _IdDepartamento;
		
		private string _Departamento;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private string _FechaCreado;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _FechaModificado;
		
		private System.Nullable<int> _CantidadRegistros;
		
		public SP_BUSCA_DEPARTAMENTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this._IdDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(100)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="NVarChar(4000)")]
		public string FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(100)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificado", DbType="NVarChar(4000)")]
		public string FechaModificado
		{
			get
			{
				return this._FechaModificado;
			}
			set
			{
				if ((this._FechaModificado != value))
				{
					this._FechaModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadRegistros", DbType="Int")]
		public System.Nullable<int> CantidadRegistros
		{
			get
			{
				return this._CantidadRegistros;
			}
			set
			{
				if ((this._CantidadRegistros != value))
				{
					this._CantidadRegistros = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_CARGOSResult
	{
		
		private decimal _IdCargo;
		
		private System.Nullable<decimal> _IdDepartamento;
		
		private string _Departamento;
		
		private string _Cargo;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private string _FechaCreado;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _FechaModificado;
		
		private System.Nullable<int> _CantidadRegistros;
		
		public SP_BUSCA_CARGOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCargo", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdCargo
		{
			get
			{
				return this._IdCargo;
			}
			set
			{
				if ((this._IdCargo != value))
				{
					this._IdCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this._IdDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(100)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(100)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="NVarChar(4000)")]
		public string FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(100)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificado", DbType="NVarChar(4000)")]
		public string FechaModificado
		{
			get
			{
				return this._FechaModificado;
			}
			set
			{
				if ((this._FechaModificado != value))
				{
					this._FechaModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadRegistros", DbType="Int")]
		public System.Nullable<int> CantidadRegistros
		{
			get
			{
				return this._CantidadRegistros;
			}
			set
			{
				if ((this._CantidadRegistros != value))
				{
					this._CantidadRegistros = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_CARGOSResult
	{
		
		private System.Nullable<decimal> _IdCargo;
		
		private System.Nullable<decimal> _IdDepartamento;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_CARGOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCargo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCargo
		{
			get
			{
				return this._IdCargo;
			}
			set
			{
				if ((this._IdCargo != value))
				{
					this._IdCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this._IdDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_TIPO_EMPLEADOResult
	{
		
		private decimal _IdTipoEmpleado;
		
		private string _TipoEmpleado;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private string _FechaCreado;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _FechaModificado;
		
		private System.Nullable<int> _CantidadRegistros;
		
		public SP_BUSCA_TIPO_EMPLEADOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEmpleado", DbType="Decimal(20,2) NOT NULL")]
		public decimal IdTipoEmpleado
		{
			get
			{
				return this._IdTipoEmpleado;
			}
			set
			{
				if ((this._IdTipoEmpleado != value))
				{
					this._IdTipoEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEmpleado", DbType="VarChar(100)")]
		public string TipoEmpleado
		{
			get
			{
				return this._TipoEmpleado;
			}
			set
			{
				if ((this._TipoEmpleado != value))
				{
					this._TipoEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="NVarChar(4000)")]
		public string FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(100)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificado", DbType="NVarChar(4000)")]
		public string FechaModificado
		{
			get
			{
				return this._FechaModificado;
			}
			set
			{
				if ((this._FechaModificado != value))
				{
					this._FechaModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadRegistros", DbType="Int")]
		public System.Nullable<int> CantidadRegistros
		{
			get
			{
				return this._CantidadRegistros;
			}
			set
			{
				if ((this._CantidadRegistros != value))
				{
					this._CantidadRegistros = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_TIPO_EMPLEADOResult
	{
		
		private System.Nullable<decimal> _IdTipoEmpleado;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_TIPO_EMPLEADOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEmpleado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> IdTipoEmpleado
		{
			get
			{
				return this._IdTipoEmpleado;
			}
			set
			{
				if ((this._IdTipoEmpleado != value))
				{
					this._IdTipoEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_TIPO_NOMINAResult
	{
		
		private decimal _IdTipoNomina;
		
		private string _TipoNomina;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuairoModifica;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private string _FechaCreado;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _FechaModificado;
		
		private System.Nullable<int> _CantidadRegistros;
		
		public SP_BUSCA_TIPO_NOMINAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoNomina", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdTipoNomina
		{
			get
			{
				return this._IdTipoNomina;
			}
			set
			{
				if ((this._IdTipoNomina != value))
				{
					this._IdTipoNomina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoNomina", DbType="VarChar(100)")]
		public string TipoNomina
		{
			get
			{
				return this._TipoNomina;
			}
			set
			{
				if ((this._TipoNomina != value))
				{
					this._TipoNomina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuairoModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuairoModifica
		{
			get
			{
				return this._UsuairoModifica;
			}
			set
			{
				if ((this._UsuairoModifica != value))
				{
					this._UsuairoModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreado", DbType="NVarChar(4000)")]
		public string FechaCreado
		{
			get
			{
				return this._FechaCreado;
			}
			set
			{
				if ((this._FechaCreado != value))
				{
					this._FechaCreado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(100)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificado", DbType="NVarChar(4000)")]
		public string FechaModificado
		{
			get
			{
				return this._FechaModificado;
			}
			set
			{
				if ((this._FechaModificado != value))
				{
					this._FechaModificado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadRegistros", DbType="Int")]
		public System.Nullable<int> CantidadRegistros
		{
			get
			{
				return this._CantidadRegistros;
			}
			set
			{
				if ((this._CantidadRegistros != value))
				{
					this._CantidadRegistros = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_TIPO_NOMINAResult
	{
		
		private System.Nullable<decimal> _IdTipoNomina;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuairoModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_TIPO_NOMINAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoNomina", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoNomina
		{
			get
			{
				return this._IdTipoNomina;
			}
			set
			{
				if ((this._IdTipoNomina != value))
				{
					this._IdTipoNomina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuairoModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuairoModifica
		{
			get
			{
				return this._UsuairoModifica;
			}
			set
			{
				if ((this._UsuairoModifica != value))
				{
					this._UsuairoModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
