#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMarket.Data.Conexion.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSMarket")]
	public partial class BDConexionListasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionListasDataContext() : 
				base(global::DSMarket.Data.Properties.Settings.Default.DSMarketConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionListasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionListasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionListasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionListasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Listas.SP_CARGAR_LISTA_TIPO_PRODUCTO")]
		public ISingleResult<SP_CARGAR_LISTA_TIPO_PRODUCTOResult> SP_CARGAR_LISTA_TIPO_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoproducto", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoproducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoproducto, descripcion);
			return ((ISingleResult<SP_CARGAR_LISTA_TIPO_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Listas.SP_CARGAR_MARCAS")]
		public ISingleResult<SP_CARGAR_MARCASResult> SP_CARGAR_MARCAS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_CARGAR_MARCASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Listas.SP_BUSCA_LISTA_TIPO_SUPLIDOR")]
		public ISingleResult<SP_BUSCA_LISTA_TIPO_SUPLIDORResult> SP_BUSCA_LISTA_TIPO_SUPLIDOR()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_BUSCA_LISTA_TIPO_SUPLIDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Listas.SP_LISTADO_CATEGORIAS")]
		public ISingleResult<SP_LISTADO_CATEGORIASResult> SP_LISTADO_CATEGORIAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoProducto);
			return ((ISingleResult<SP_LISTADO_CATEGORIASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Listas.SP_LISTADO_UNIDAD_MEDIDA")]
		public ISingleResult<SP_LISTADO_UNIDAD_MEDIDAResult> SP_LISTADO_UNIDAD_MEDIDA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_LISTADO_UNIDAD_MEDIDAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Listas.SP_CARGAR_LISTA_MODELOS")]
		public ISingleResult<SP_CARGAR_LISTA_MODELOSResult> SP_CARGAR_LISTA_MODELOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMarca", DbType="Decimal(20,0)")] System.Nullable<decimal> idMarca)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMarca);
			return ((ISingleResult<SP_CARGAR_LISTA_MODELOSResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_CARGAR_LISTA_TIPO_PRODUCTOResult
	{
		
		private decimal _IdTipoproducto;
		
		private string _Descripcion;
		
		public SP_CARGAR_LISTA_TIPO_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoproducto", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdTipoproducto
		{
			get
			{
				return this._IdTipoproducto;
			}
			set
			{
				if ((this._IdTipoproducto != value))
				{
					this._IdTipoproducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_CARGAR_MARCASResult
	{
		
		private decimal _IdMarca;
		
		private string _Descripcion;
		
		public SP_CARGAR_MARCASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMarca", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdMarca
		{
			get
			{
				return this._IdMarca;
			}
			set
			{
				if ((this._IdMarca != value))
				{
					this._IdMarca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_LISTA_TIPO_SUPLIDORResult
	{
		
		private decimal _IdTipoSuplidor;
		
		private string _Descripcion;
		
		public SP_BUSCA_LISTA_TIPO_SUPLIDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoSuplidor", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdTipoSuplidor
		{
			get
			{
				return this._IdTipoSuplidor;
			}
			set
			{
				if ((this._IdTipoSuplidor != value))
				{
					this._IdTipoSuplidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_LISTADO_CATEGORIASResult
	{
		
		private decimal _IdCategoria;
		
		private string _Descripcion;
		
		public SP_LISTADO_CATEGORIASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_LISTADO_UNIDAD_MEDIDAResult
	{
		
		private decimal _IdUnidadMedida;
		
		private string _Descripcion;
		
		public SP_LISTADO_UNIDAD_MEDIDAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnidadMedida", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdUnidadMedida
		{
			get
			{
				return this._IdUnidadMedida;
			}
			set
			{
				if ((this._IdUnidadMedida != value))
				{
					this._IdUnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_CARGAR_LISTA_MODELOSResult
	{
		
		private decimal _IdModelo;
		
		private string _Descripcion;
		
		public SP_CARGAR_LISTA_MODELOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModelo", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdModelo
		{
			get
			{
				return this._IdModelo;
			}
			set
			{
				if ((this._IdModelo != value))
				{
					this._IdModelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
