<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionEmpresaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;Persist Security Info=True;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="Empresa.SP_MANTENIMIENTO_CLIENTES" Method="SP_MANTENIMIENTO_CLIENTES">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoCredito" Parameter="montoCredito" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EnvioEmail" Parameter="envioEmail" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CLIENTESResult">
      <Column Name="IdCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MontoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EnvioEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CLIENTES" Method="SP_BUSCA_CLIENTES">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnvioEmail" Parameter="envioEmail" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CLIENTESResult">
      <Column Name="IdCliente" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="EnvioEmail0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnvioEmail" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="MontoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadClientes" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_COMPRAS_SUPLIDORES" Method="SP_MANTENIMIENTO_COMPRAS_SUPLIDORES">
    <Parameter Name="IdCompraSuplidor" Parameter="idCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdSuplidor" Parameter="idSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNCCedula" Parameter="rNCCedula" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoBienesServicios" Parameter="idTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NCF" Parameter="nCF" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NCFModificado" Parameter="nCFModificado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaComprobante" Parameter="fechaComprobante" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaPago" Parameter="fechaPago" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MontoFacturadoServicios" Parameter="montoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoFacturadoBienes" Parameter="montoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalMontoFacturado" Parameter="totalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISFacturado" Parameter="iTBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISRetenido" Parameter="iTBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISSujetoProporcionalidad" Parameter="iTBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISLlevadoCosto" Parameter="iTBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPorAdelantar" Parameter="iTBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPercibidoCompras" Parameter="iTBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoRetencionISR" Parameter="idTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoRetencionRenta" Parameter="montoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ISRPercibidoCompras" Parameter="iSRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoSelectivoConsumo" Parameter="impuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OtrosImpuestosTasa" Parameter="otrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPropinaLegal" Parameter="montoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdFormaPago" Parameter="idFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCreado" Parameter="fechaCreado" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_COMPRAS_SUPLIDORESResult">
      <Column Name="IdCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="RNCCedula" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NCFModificado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaComprobante" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MontoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="MontoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ISRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_REGISTROS_COMPRA_SUPLIDORES" Method="SP_BUSCA_REGISTROS_COMPRA_SUPLIDORES">
    <Parameter Name="IdCompraSuplidor" Parameter="idCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdSuplidor" Parameter="idSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNCCedula" Parameter="rNCCedula" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaCreadoDesde" Parameter="fechaCreadoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCreadoHasta" Parameter="fechaCreadoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_REGISTROS_COMPRA_SUPLIDORESResult">
      <Column Name="IdCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoSuplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Suplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNCCedula" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoBienesServicios" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoBienesServicio" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NCFModificado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaComprobante0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaComprobante" Type="System.String" DbType="VarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="FechaPago0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.String" DbType="VarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="MontoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoRetencionISR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoRetencionISR" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="MontoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ISRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FormaPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaCreado0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_DEPARTAMENTOS" Method="SP_MANTENIMIENTO_DEPARTAMENTOS">
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_DEPARTAMENTOSResult">
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_DEPARTAMENTOS" Method="SP_BUSCA_DEPARTAMENTOS">
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_DEPARTAMENTOSResult">
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>