<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConecionServicioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.26.24.199;Initial Catalog=DSMarket;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="Servicio.SP_MANTENIMIENTO_HISTORIAL_PRODUCTO_INVENTARIO" Method="SP_MANTENIMIENTO_HISTORIAL_PRODUCTO_INVENTARIO">
    <Parameter Name="IdHistorialProducto" Parameter="idHistorialProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORIAL_PRODUCTO_INVENTARIOResult">
      <Column Name="IdHistorialProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_VALIDAR_FACTURA_ANULADA" Method="SP_VALIDAR_FACTURA_ANULADA">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_VALIDAR_FACTURA_ANULADAResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_SACAR_GANANCIA_FACTURACION" Method="SP_SACAR_GANANCIA_FACTURACION">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusFacturacion" Parameter="idEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_SACAR_GANANCIA_FACTURACIONResult">
      <Column Name="IdEstatusFacturacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdFactura" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Acumulativo" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadVendida" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalVenta" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalPrecioCompra" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Ganancia" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_HISTORIAL_PRODUCTO" Method="SP_BUSCA_HISTORIAL_PRODUCTO">
    <Parameter Name="IdHistorialProducto" Parameter="idHistorialProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_HISTORIAL_PRODUCTOResult">
      <Column Name="IdHistorialProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdMarca" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdModelo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoSuplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Suplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoBarra" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Referencia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="AfectaOferta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductoAcumulativo0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductoAcumulativo" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="LlevaImagen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="AplicaParaimpuesto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PrecioOriginal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_TIPO_PAGO" Method="SP_BUSCA_TIPO_PAGO">
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_PAGOResult">
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="BloqueaMonto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BloqueaMonto" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ImpuestoAdicional0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImpuestoAdicional" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PorcentajeEntero0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorcentajeEntero" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_MANTENIMIENTO_TIPO_PAGO" Method="SP_MANTENIMIENTO_TIPO_PAGO">
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="BloqueaMonto" Parameter="bloqueaMonto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ImpuestoAdicional" Parameter="impuestoAdicional" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorcentajeEntero" Parameter="porcentajeEntero" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Valor" Parameter="valor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CodigoTipoPago" Parameter="codigoTipoPago" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_PAGOResult">
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BloqueaMonto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImpuestoAdicional" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorcentajeEntero" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_OBSERVACIONES" Method="SP_BUSCA_OBSERVACIONES">
    <Parameter Name="IdObservacion" Parameter="idObservacion" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_OBSERVACIONESResult">
      <Column Name="IdObServacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_MODIFICAR_OBSERVACION" Method="SP_MODIFICAR_OBSERVACION">
    <Parameter Name="IdObservacion" Parameter="idObservacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Observacion" Parameter="observacion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_OBSERVACIONResult">
      <Column Name="IdObservacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_FACTURACION_ESPEJO" Method="SP_BUSCA_FACTURACION_ESPEJO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_FACTURACION_ESPEJOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="AgregarCliente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuscarCliente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoVenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCantidadDias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadDias" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RncConsulta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NoCotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="MontoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FacturarCotizar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacturaPuntoVenta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FormatoFactura" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BloqueaControles" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CantidadDiasGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoIngreso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoIngreso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTiempoGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoTiempoGarantia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_FACTURA_MINIMIZADAS" Method="SP_BUSCA_FACTURA_MINIMIZADAS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Rnc" Parameter="rnc" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_FACTURA_MINIMIZADASResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="AgregarCliente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuscarCliente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoVenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCantidadDias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadDias" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RncConsulta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NoCotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="MontoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FacturarCotizar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacturaPuntoVenta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FormatoFactura" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BloqueaControles" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CantidadDiasGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoIngreso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoIngreso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoTiempoGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoTiempoGarantia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidadregistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_TIPO_TIEMPO_GARANTIA" Method="SP_BUSCA_TIPO_TIEMPO_GARANTIA">
    <Parameter Name="IdTipoTiempoGarantia" Parameter="idTipoTiempoGarantia" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_TIEMPO_GARANTIAResult">
      <Column Name="IdTipoTiempoGarantia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoTiempoGarantia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TiempoGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_MODIFICAR_TIPO_TIEMPO_GARANTIA" Method="SP_MODIFICAR_TIPO_TIEMPO_GARANTIA">
    <Parameter Name="IdTipoTiempoGarantia" Parameter="idTipoTiempoGarantia" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoTiempoGarantia" Parameter="tipoTiempoGarantia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TiempoGarantia" Parameter="tiempoGarantia" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_TIPO_TIEMPO_GARANTIAResult">
      <Column Name="IdTipoTiempoGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoTiempoGarantia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TiempoGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Historial.SP_BUSCA_HISTORIAL_FACTURACION" Method="SP_BUSCA_HISTORIAL_FACTURACION">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusFacturacion" Parameter="idEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_HISTORIAL_FACTURACIONResult">
      <Column Name="Cliente" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EstatusFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdFactura" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdEstatusFacturacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DescripcionComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdTipoVenta" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadDias" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IdCantidadDias" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIngreso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoIngreso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaFacturacion0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadProductos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadServicios" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadArticulos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(22,2)" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(22,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(22,2)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(22,2)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(22,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PorcientoTipoPago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoImpuestoTipoPago" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoImpuestoComprobante" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoImpuestoComprobante" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(22,2)" CanBeNull="true" />
      <Column Name="AplicaGarantia0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AplicaGarantia" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DiasGarantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoTiempoGarantia0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoTiempoGarantia" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_REGISTRO_PRODUCTO_REFERENCIA" Method="SP_BUSCA_REGISTRO_PRODUCTO_REFERENCIA">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Referencia" Parameter="referencia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DescripcionProducto" Parameter="descripcionProducto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_REGISTRO_PRODUCTO_REFERENCIAResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdFactura" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Referencia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DescripcionTipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadVendida" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Acumulativo" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ProductoInventario" Type="System.String" DbType="VarChar(28) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_PRODUCTOS_AGREGADOS" Method="SP_BUSCA_PRODUCTOS_AGREGADOS">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_PRODUCTOS_AGREGADOSResult">
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Referencia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DescripcionTipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="DescripcionTipoProducto1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Acumulativo" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ConectorProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="AplicaImpuesto" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadProductos" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="CantidadServicios" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalImpuesto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_COMISION_EMPLEADOS" Method="SP_PROCESAR_COMISION_EMPLEADOS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="PrecioProducto" Parameter="precioProducto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="DescuentoAplicado" Parameter="descuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ComisionEmpleado" Parameter="comisionEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="NumeroConectorOperacion" Parameter="numeroConectorOperacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ConectorProducto" Parameter="conectorProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_COMISION_EMPLEADOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PrecioProducto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="NumeroConectorOperacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ConectorProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_COMISIONES_EMPLEADOS" Method="SP_BUSCA_COMISIONES_EMPLEADOS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConectorProducto" Parameter="numeroConectorProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConectorOperacion" Parameter="numeroConectorOperacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Numeropagina" Parameter="numeropagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_COMISIONES_EMPLEADOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Empleado" Type="System.String" DbType="VarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrecioProducto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionEmpleado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionPagar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="NumeroConectorOperacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ConectorProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadVentas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadServicios" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_ASIGNA_FECHA_MANUAL_FACTURACION" Method="SP_ASIGNA_FECHA_MANUAL_FACTURACION">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaFactura" Parameter="fechaFactura" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_ASIGNA_FECHA_MANUAL_FACTURACIONResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaFactura" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_INFORMACION_FACTURACION" Method="SP_PROCESAR_INFORMACION_FACTURACION">
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="FacturadoA" Parameter="facturadoA" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="TotalProductos" Parameter="totalProductos" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalServicios" Parameter="totalServicios" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalItems" Parameter="totalItems" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubTotal" Parameter="subTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="DescuentoTotal" Parameter="descuentoTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoTotal" Parameter="impuestoTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalGeneral" Parameter="totalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cambio" Parameter="cambio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdMoneda" Parameter="idMoneda" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FechaFacturacion" Parameter="fechaFacturacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ValidoHasta" Parameter="validoHasta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NumeroComprobante" Parameter="numeroComprobante" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_FACTURACIONResult">
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FacturadoA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="TotalProductos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalServicios" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdMoneda" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroComprobante" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_INFORMACION_FACTURA_PREVIEW" Method="SP_PROCESAR_INFORMACION_FACTURA_PREVIEW">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descuento" Parameter="descuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoImpuesto" Parameter="porcientoImpuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_FACTURA_PREVIEWResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCAR_FACTURACION_PREVIEW" Method="SP_BUSCAR_FACTURACION_PREVIEW">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCAR_FACTURACION_PREVIEWResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalProducto" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TotalServicio" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TotalItems" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalSubTotal" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalImpuesto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_BUSCA_MONEDAS" Method="SP_BUSCA_MONEDAS">
    <Parameter Name="IdMoneda" Parameter="idMoneda" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Moneda" Parameter="moneda" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_MONEDASResult">
      <Column Name="IdMoneda" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sigla" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="PorDefecto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_INFORMACION_MONEDA" Method="SP_PROCESAR_INFORMACION_MONEDA">
    <Parameter Name="IdMoneda" Parameter="idMoneda" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Sigla" Parameter="sigla" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="PorDefecto" Parameter="porDefecto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_MONEDAResult">
      <Column Name="IdMoneda" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sigla" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_INFORMACION_FACTURACION_DETALLE" Method="SP_PROCESAR_INFORMACION_FACTURACION_DETALLE">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Descuento" Parameter="descuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="PorcientoImpuesto" Parameter="porcientoImpuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubTotal" Parameter="subTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdRegistroRespaldo" Parameter="idRegistroRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConectorItemRespaldo" Parameter="numeroConectorItemRespaldo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IdTipoProductoRespaldo" Parameter="idTipoProductoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCategoriaRespaldo" Parameter="idCategoriaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMarcaRespaldo" Parameter="idMarcaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidorRespaldo" Parameter="idTipoSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdSuplidorRespaldo" Parameter="idSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="DescripcionRespaldo" Parameter="descripcionRespaldo" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="CodigoBarraRespaldo" Parameter="codigoBarraRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ReferenciaRespaldo" Parameter="referenciaRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NumeroSeguimientoRespaldo" Parameter="numeroSeguimientoRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoProductoRespaldo" Parameter="codigoProductoRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PrecioCompraRespaldo" Parameter="precioCompraRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PrecioVentaRespaldo" Parameter="precioVentaRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="StockRespaldo" Parameter="stockRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="StockMinimoRespaldo" Parameter="stockMinimoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="UnidadMedidaRespaldo" Parameter="unidadMedidaRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ModeloRespaldo" Parameter="modeloRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ColorRespaldo" Parameter="colorRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CondicionRespaldo" Parameter="condicionRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CapacidadRespaldo" Parameter="capacidadRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AplicaParaImpuestoRespaldo" Parameter="aplicaParaImpuestoRespaldo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TieneImagenRespaldo" Parameter="tieneImagenRespaldo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LlevaGarantiaRespaldo" Parameter="llevaGarantiaRespaldo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdTipoGarantiaRespaldo" Parameter="idTipoGarantiaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TiempoGarantiaRespaldo" Parameter="tiempoGarantiaRespaldo" Type="System.Int32" DbType="Int" />
    <Parameter Name="ComentarioItemRespaldo" Parameter="comentarioItemRespaldo" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="UsuarioAdicionaRespaldo" Parameter="usuarioAdicionaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaAdicionaRespaldo" Parameter="fechaAdicionaRespaldo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UsuarioModificaRespaldo" Parameter="usuarioModificaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaModificaRespaldo" Parameter="fechaModificaRespaldo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaIngresoRespaldo" Parameter="fechaIngresoRespaldo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_FACTURACION_DETALLEResult">
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdRegistroRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConectorItemRespaldo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdTipoProductoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCategoriaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdMarcaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescripcionRespaldo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoBarraRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReferenciaRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroSeguimientoRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoProductoRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrecioCompraRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVentaRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="StockRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="StockMinimoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UnidadMedidaRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ModeloRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ColorRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CondicionRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CapacidadRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AplicaParaImpuestoRespaldo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TieneImagenRespaldo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LlevaGarantiaRespaldo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoGarantiaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TiempoGarantiaRespaldo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComentarioItemRespaldo" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="UsuarioAdicionaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdicionaRespaldo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModificaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModificaRespaldo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaIngresoRespaldo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_INFORMCION_COTIZACION" Method="SP_PROCESAR_INFORMCION_COTIZACION">
    <Parameter Name="NumeroCotizacion" Parameter="numeroCotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CotizacoA" Parameter="cotizacoA" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="TotalProductos" Parameter="totalProductos" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalServicios" Parameter="totalServicios" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalItems" Parameter="totalItems" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubTotal" Parameter="subTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="DescuentoTotal" Parameter="descuentoTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoTotal" Parameter="impuestoTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalGeneral" Parameter="totalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cambio" Parameter="cambio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdMoneda" Parameter="idMoneda" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCotizacion" Parameter="fechaCotizacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMCION_COTIZACIONResult">
      <Column Name="NumeroCotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CotizacoA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="TotalProductos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalServicios" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdMoneda" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCotizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_PROCESAR_INFORMACION_COTIZACION_DETALLE" Method="SP_PROCESAR_INFORMACION_COTIZACION_DETALLE">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Descuento" Parameter="descuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="PorcientoImpuesto" Parameter="porcientoImpuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubTotal" Parameter="subTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdRegistroRespaldo" Parameter="idRegistroRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConectorItemRespaldo" Parameter="numeroConectorItemRespaldo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IdTipoProductoRespaldo" Parameter="idTipoProductoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCategoriaRespaldo" Parameter="idCategoriaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMarcaRespaldo" Parameter="idMarcaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidorRespaldo" Parameter="idTipoSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdSuplidorRespaldo" Parameter="idSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="DescripcionRespaldo" Parameter="descripcionRespaldo" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="CodigoBarraRespaldo" Parameter="codigoBarraRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ReferenciaRespaldo" Parameter="referenciaRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NumeroSeguimientoRespaldo" Parameter="numeroSeguimientoRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoProductoRespaldo" Parameter="codigoProductoRespaldo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PrecioCompraRespaldo" Parameter="precioCompraRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PrecioVentaRespaldo" Parameter="precioVentaRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="StockRespaldo" Parameter="stockRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="StockMinimoRespaldo" Parameter="stockMinimoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="UnidadMedidaRespaldo" Parameter="unidadMedidaRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ModeloRespaldo" Parameter="modeloRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ColorRespaldo" Parameter="colorRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CondicionRespaldo" Parameter="condicionRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CapacidadRespaldo" Parameter="capacidadRespaldo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AplicaParaImpuestoRespaldo" Parameter="aplicaParaImpuestoRespaldo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TieneImagenRespaldo" Parameter="tieneImagenRespaldo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LlevaGarantiaRespaldo" Parameter="llevaGarantiaRespaldo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdTipoGarantiaRespaldo" Parameter="idTipoGarantiaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TiempoGarantiaRespaldo" Parameter="tiempoGarantiaRespaldo" Type="System.Int32" DbType="Int" />
    <Parameter Name="ComentarioItemRespaldo" Parameter="comentarioItemRespaldo" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="UsuarioAdicionaRespaldo" Parameter="usuarioAdicionaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaAdicionaRespaldo" Parameter="fechaAdicionaRespaldo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UsuarioModificaRespaldo" Parameter="usuarioModificaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaModificaRespaldo" Parameter="fechaModificaRespaldo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaIngresoRespaldo" Parameter="fechaIngresoRespaldo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_COTIZACION_DETALLEResult">
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdRegistroRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConectorItemRespaldo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdTipoProductoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCategoriaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdMarcaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdSuplidorRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescripcionRespaldo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoBarraRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReferenciaRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroSeguimientoRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoProductoRespaldo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrecioCompraRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVentaRespaldo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="StockRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="StockMinimoRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UnidadMedidaRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ModeloRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ColorRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CondicionRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CapacidadRespaldo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AplicaParaImpuestoRespaldo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TieneImagenRespaldo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LlevaGarantiaRespaldo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoGarantiaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TiempoGarantiaRespaldo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComentarioItemRespaldo" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="UsuarioAdicionaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdicionaRespaldo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModificaRespaldo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModificaRespaldo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaIngresoRespaldo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_SACAR_NUMERO_FACTURA" Method="SP_SACAR_NUMERO_FACTURA">
    <Parameter Name="NumeroCoector" Parameter="numeroCoector" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_SACAR_NUMERO_FACTURAResult">
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Servicio.SP_SACAR_NUMERO_COTIZACION" Method="SP_SACAR_NUMERO_COTIZACION">
    <Parameter Name="NumeroCoector" Parameter="numeroCoector" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_SACAR_NUMERO_COTIZACIONResult">
      <Column Name="NumeroCotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>