#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMarket.Data.Conexion.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSMarket")]
	public partial class BDConexionCajaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionCajaDataContext() : 
				base(global::DSMarket.Data.Properties.Settings.Default.DSMarketConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionCajaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionCajaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionCajaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionCajaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_ESTATUS_CAJA")]
		public ISingleResult<SP_ESTATUS_CAJAResult> SP_ESTATUS_CAJA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ESTATUS_CAJAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_AFECTAR_CAJA_GENERAL")]
		public ISingleResult<SP_AFECTAR_CAJA_GENERALResult> SP_AFECTAR_CAJA_GENERAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoActual", DbType="Decimal(20,2)")] System.Nullable<decimal> montoActual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCaja, descripcion, montoActual, estatus, accion);
			return ((ISingleResult<SP_AFECTAR_CAJA_GENERALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_GUARDAR_HISTORIAL_CAJA")]
		public ISingleResult<SP_GUARDAR_HISTORIAL_CAJAResult> SP_GUARDAR_HISTORIAL_CAJA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdHistorialCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idHistorialCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monto", DbType="Decimal(20,2)")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Concepto", DbType="VarChar(200)")] string concepto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroReferencia", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPago", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoPago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idHistorialCaja, idCaja, monto, concepto, fecha, idUsuario, numeroReferencia, idTipoPago, accion);
			return ((ISingleResult<SP_GUARDAR_HISTORIAL_CAJAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_BUSCA_HISTORIAL_CAJA")]
		public ISingleResult<SP_BUSCA_HISTORIAL_CAJAResult> SP_BUSCA_HISTORIAL_CAJA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdHistorialCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idHistorialCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaHasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idHistorialCaja, idCaja, fechaDesde, fechaHasta);
			return ((ISingleResult<SP_BUSCA_HISTORIAL_CAJAResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_ESTATUS_CAJAResult
	{
		
		private decimal _IdCaja;
		
		private string _Caja;
		
		private System.Nullable<decimal> _MontoActual;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		public SP_ESTATUS_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caja", DbType="VarChar(100)")]
		public string Caja
		{
			get
			{
				return this._Caja;
			}
			set
			{
				if ((this._Caja != value))
				{
					this._Caja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoActual", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoActual
		{
			get
			{
				return this._MontoActual;
			}
			set
			{
				if ((this._MontoActual != value))
				{
					this._MontoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
	
	public partial class SP_AFECTAR_CAJA_GENERALResult
	{
		
		private System.Nullable<decimal> _IdCaja;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _MontoActual;
		
		private System.Nullable<bool> _Estatus;
		
		public SP_AFECTAR_CAJA_GENERALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoActual", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoActual
		{
			get
			{
				return this._MontoActual;
			}
			set
			{
				if ((this._MontoActual != value))
				{
					this._MontoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
	
	public partial class SP_GUARDAR_HISTORIAL_CAJAResult
	{
		
		private System.Nullable<decimal> _IdHistorialCaja;
		
		private System.Nullable<decimal> _IdCaja;
		
		private System.Nullable<decimal> _Monto;
		
		private string _Concepto;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private System.Nullable<decimal> _NumeroReferencia;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		public SP_GUARDAR_HISTORIAL_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHistorialCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdHistorialCaja
		{
			get
			{
				return this._IdHistorialCaja;
			}
			set
			{
				if ((this._IdHistorialCaja != value))
				{
					this._IdHistorialCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(200)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReferencia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroReferencia
		{
			get
			{
				return this._NumeroReferencia;
			}
			set
			{
				if ((this._NumeroReferencia != value))
				{
					this._NumeroReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_HISTORIAL_CAJAResult
	{
		
		private decimal _IdHistorialCaja;
		
		private System.Nullable<decimal> _IdCaja;
		
		private System.Nullable<decimal> _Monto;
		
		private string _Concepto;
		
		private System.Nullable<System.DateTime> _Fecha0;
		
		private string _Fecha;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private string _CreadoPor;
		
		private System.Nullable<decimal> _NumeroReferencia;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private string _TipoPago;
		
		public SP_BUSCA_HISTORIAL_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHistorialCaja", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdHistorialCaja
		{
			get
			{
				return this._IdHistorialCaja;
			}
			set
			{
				if ((this._IdHistorialCaja != value))
				{
					this._IdHistorialCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(200)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha0", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha0
		{
			get
			{
				return this._Fecha0;
			}
			set
			{
				if ((this._Fecha0 != value))
				{
					this._Fecha0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(4000)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(100)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReferencia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroReferencia
		{
			get
			{
				return this._NumeroReferencia;
			}
			set
			{
				if ((this._NumeroReferencia != value))
				{
					this._NumeroReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPago", DbType="VarChar(100)")]
		public string TipoPago
		{
			get
			{
				return this._TipoPago;
			}
			set
			{
				if ((this._TipoPago != value))
				{
					this._TipoPago = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
