#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMarket.Data.Conexion.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSMarket")]
	public partial class BDConexionConfiguracionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionConfiguracionDataContext() : 
				base(global::DSMarket.Data.Properties.Settings.Default.DSMarketConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionConfiguracionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Configuracion.SP_BUSCA_LISTAS")]
		public ISingleResult<SP_BUSCA_LISTASResult> SP_BUSCA_LISTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreLista", DbType="VarChar(150)")] string nombreLista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerFiltro", DbType="VarChar(150)")] string primerFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoFiltro", DbType="VarChar(150)")] string segundoFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TerceFiltro", DbType="VarChar(150)")] string terceFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuartoFiltro", DbType="VarChar(150)")] string cuartoFiltro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuintoFiltro", DbType="VarChar(150)")] string quintoFiltro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreLista, primerFiltro, segundoFiltro, terceFiltro, cuartoFiltro, quintoFiltro);
			return ((ISingleResult<SP_BUSCA_LISTASResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_BUSCA_LISTASResult
	{
		
		private string _Descripcion;
		
		private string _PrimerValor;
		
		private string _SegundoValor;
		
		private string _TerceValor;
		
		public SP_BUSCA_LISTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerValor", DbType="VarChar(150)")]
		public string PrimerValor
		{
			get
			{
				return this._PrimerValor;
			}
			set
			{
				if ((this._PrimerValor != value))
				{
					this._PrimerValor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoValor", DbType="VarChar(150)")]
		public string SegundoValor
		{
			get
			{
				return this._SegundoValor;
			}
			set
			{
				if ((this._SegundoValor != value))
				{
					this._SegundoValor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerceValor", DbType="VarChar(150)")]
		public string TerceValor
		{
			get
			{
				return this._TerceValor;
			}
			set
			{
				if ((this._TerceValor != value))
				{
					this._TerceValor = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
