<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionListasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;Persist Security Info=True;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="Listas.SP_CARGAR_LISTA_TIPO_PRODUCTO" Method="SP_CARGAR_LISTA_TIPO_PRODUCTO">
    <Parameter Name="IdTipoproducto" Parameter="idTipoproducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_CARGAR_LISTA_TIPO_PRODUCTOResult">
      <Column Name="IdTipoproducto" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_LISTA_TIPO_SUPLIDOR" Method="SP_BUSCA_LISTA_TIPO_SUPLIDOR">
    <ElementType Name="SP_BUSCA_LISTA_TIPO_SUPLIDORResult">
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_CATEGORIAS" Method="SP_LISTADO_CATEGORIAS">
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_LISTADO_CATEGORIASResult">
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_UNIDAD_MEDIDA" Method="SP_LISTADO_UNIDAD_MEDIDA">
    <ElementType Name="SP_LISTADO_UNIDAD_MEDIDAResult">
      <Column Name="IdUnidadMedida" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_CARGAR_LISTA_MODELOS" Method="SP_CARGAR_LISTA_MODELOS">
    <Parameter Name="IdMarca" Parameter="idMarca" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_CARGAR_LISTA_MODELOSResult">
      <Column Name="IdModelo" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTAS_SUPLIDORES" Method="SP_LISTAS_SUPLIDORES">
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_LISTAS_SUPLIDORESResult">
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_COMPROBANTE_FISCALES" Method="SP_BUSCA_COMPROBANTE_FISCALES">
    <ElementType Name="SP_BUSCA_COMPROBANTE_FISCALESResult">
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Comprbante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_LISTA_COMPROBANTE_NULOS" Method="SP_BUSCA_LISTA_COMPROBANTE_NULOS">
    <ElementType Name="SP_BUSCA_LISTA_COMPROBANTE_NULOSResult">
      <Column Name="IdComprobanteNulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_TIPO_IDENTIFICACION" Method="SP_LISTADO_TIPO_IDENTIFICACION">
    <ElementType Name="SP_LISTADO_TIPO_IDENTIFICACIONResult">
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_TIPO_VENTA" Method="SP_BUSCA_TIPO_VENTA">
    <ElementType Name="SP_BUSCA_TIPO_VENTAResult">
      <Column Name="IdTipoVenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_CANTIDAD_DIAS" Method="SP_CANTIDAD_DIAS">
    <ElementType Name="SP_CANTIDAD_DIASResult">
      <Column Name="IdCantidadDias" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadDias" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_LISTADO_ESTATUS_FACTURACION" Method="SP_BUSCA_LISTADO_ESTATUS_FACTURACION">
    <ElementType Name="SP_BUSCA_LISTADO_ESTATUS_FACTURACIONResult">
      <Column Name="IdEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_NIVEL_ACCESO" Method="SP_LISTADO_NIVEL_ACCESO">
    <ElementType Name="SP_LISTADO_NIVEL_ACCESOResult">
      <Column Name="IdNivelAcceso" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTA_USUARIOS" Method="SP_LISTA_USUARIOS">
    <ElementType Name="SP_LISTA_USUARIOSResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Persona" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_LISTA_TIPO_MAIL" Method="SP_BUSCA_LISTA_TIPO_MAIL">
    <ElementType Name="SP_BUSCA_LISTA_TIPO_MAILResult">
      <Column Name="IdTipoMail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoMail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_TIPO_PAGO" Method="SP_LISTADO_TIPO_PAGO">
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_LISTADO_TIPO_PAGOResult">
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BloqueaMonto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImpuestoAdicional" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorcentajeEntero" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_CARGAR_MARCAS" Method="SP_CARGAR_MARCAS">
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_CARGAR_MARCASResult">
      <Column Name="IdMarca" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_BIENES_SERVICIOS" Method="SP_LISTADO_BIENES_SERVICIOS">
    <ElementType Name="SP_LISTADO_BIENES_SERVICIOSResult">
      <Column Name="IdTipoBienesServicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_LISTADO_TIPO_RETENCION_ISR" Method="SP_LISTADO_TIPO_RETENCION_ISR">
    <ElementType Name="SP_LISTADO_TIPO_RETENCION_ISRResult">
      <Column Name="IdTipoRetencionISR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Listas.SP_BUSCA_LISTA_TIPO_INGRESOS" Method="SP_BUSCA_LISTA_TIPO_INGRESOS">
    <ElementType Name="SP_BUSCA_LISTA_TIPO_INGRESOSResult">
      <Column Name="IdTipoIngreso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>