<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionConfiguracionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Configuracion.SP_BUSCA_LISTAS" Method="SP_BUSCA_LISTAS">
    <Parameter Name="NombreLista" Parameter="nombreLista" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PrimerFiltro" Parameter="primerFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="SegundoFiltro" Parameter="segundoFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="TerceFiltro" Parameter="terceFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="CuartoFiltro" Parameter="cuartoFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="QuintoFiltro" Parameter="quintoFiltro" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_BUSCA_LISTASResult">
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrimerValor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SegundoValor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="TerceValor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_SACAR_INFORMACION_EMPRESA" Method="SP_SACAR_INFORMACION_EMPRESA">
    <ElementType Name="SP_SACAR_INFORMACION_EMPRESAResult">
      <Column Name="IdInformacionEmpresa" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagran" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdLogoEmpresa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogoEmpresa" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MODIFICAR_INFORMACION_EMPRESA" Method="SP_MODIFICAR_INFORMACION_EMPRESA">
    <Parameter Name="IdInformacionEmpresa" Parameter="idInformacionEmpresa" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombreEmpresa" Parameter="nombreEmpresa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email2" Parameter="email2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Facebook" Parameter="facebook" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Instagran" Parameter="instagran" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="IdLogoEmpresa" Parameter="idLogoEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_INFORMACION_EMPRESAResult">
      <Column Name="IdInformacionEmpresa" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagran" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdLogoEmpresa" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCA_CONFIGURACION_GENERAL" Method="SP_BUSCA_CONFIGURACION_GENERAL">
    <Parameter Name="IdConfiguracionGeneral" Parameter="idConfiguracionGeneral" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CONFIGURACION_GENERALResult">
      <Column Name="IdConfiguracionGeneral" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>