<?xml version="1.0" encoding="utf-8"?><Database Name="DSMarket" Class="BDConexionConfiguracionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=DSMarket;Persist Security Info=True;User ID=sa" SettingsObjectName="DSMarket.Data.Properties.Settings" SettingsPropertyName="DSMarketConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="Configuracion.SP_BUSCA_LISTAS" Method="SP_BUSCA_LISTAS">
    <Parameter Name="NombreLista" Parameter="nombreLista" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PrimerFiltro" Parameter="primerFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="SegundoFiltro" Parameter="segundoFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="TerceFiltro" Parameter="terceFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="CuartoFiltro" Parameter="cuartoFiltro" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="QuintoFiltro" Parameter="quintoFiltro" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_BUSCA_LISTASResult">
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrimerValor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SegundoValor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="TerceValor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_SACAR_INFORMACION_EMPRESA" Method="SP_SACAR_INFORMACION_EMPRESA">
    <ElementType Name="SP_SACAR_INFORMACION_EMPRESAResult">
      <Column Name="IdInformacionEmpresa" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagran" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdLogoEmpresa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogoEmpresa" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_GENERAR_COMPROBANTE_FISCAL" Method="SP_GENERAR_COMPROBANTE_FISCAL">
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_GENERAR_COMPROBANTE_FISCALResult">
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCA_COMPROBANTES_FISCALES" Method="SP_BUSCA_COMPROBANTES_FISCALES">
    <Parameter Name="IdComprobanteFiscales" Parameter="idComprobanteFiscales" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_COMPROBANTES_FISCALESResult">
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Serie" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="SecuenciaInicial" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="SecuenciaFinal" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Limite" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PorDefecto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Posiciones" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MANTENIMIENTO_COMPROBANTE_FISCALES" Method="SP_MANTENIMIENTO_COMPROBANTE_FISCALES">
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Serie" Parameter="serie" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="TipoComprobante" Parameter="tipoComprobante" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SecuenciaInicial" Parameter="secuenciaInicial" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SecuenciaFinal" Parameter="secuenciaFinal" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Limite" Parameter="limite" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ValidoHasta" Parameter="validoHasta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PorDefecto" Parameter="porDefecto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Posiciones" Parameter="posiciones" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult">
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Serie" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecuenciaInicial" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecuenciaFinal" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Limite" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Posiciones" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCA_CONFIGURACION_GENERAL" Method="SP_BUSCA_CONFIGURACION_GENERAL">
    <Parameter Name="IdConfiguracionGeneral" Parameter="idConfiguracionGeneral" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CONFIGURACION_GENERALResult">
      <Column Name="IdConfiguracionGeneral" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadActivos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadInactivos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MANTENIMIENTO_CONFIGURACION_GENERAL" Method="SP_MANTENIMIENTO_CONFIGURACION_GENERAL">
    <Parameter Name="IdConfiguracionGeneral" Parameter="idConfiguracionGeneral" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CONFIGURACION_GENERALResult">
      <Column Name="IdConfiguracionGeneral" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCA_IMPUESTO_VENTA" Method="SP_BUSCA_IMPUESTO_VENTA">
    <Parameter Name="IdImpuesto" Parameter="idImpuesto" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_IMPUESTO_VENTAResult">
      <Column Name="IdImpuesto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Operacion0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Operacion" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_SACAR_RUTA_REPORTE" Method="SP_SACAR_RUTA_REPORTE">
    <Parameter Name="IdReporte" Parameter="idReporte" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACAR_RUTA_REPORTEResult">
      <Column Name="IdReporte" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RutaReporte" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_MANTENIMIENTO_RUTA_REPORTE" Method="SP_MANTENIMIENTO_RUTA_REPORTE">
    <Parameter Name="IdReporte" Parameter="idReporte" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RutaReporte" Parameter="rutaReporte" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_RUTA_REPORTEResult">
      <Column Name="IdReporte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RutaReporte" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_PROCESAR_CUADRE_CAJA" Method="SP_PROCESAR_CUADRE_CAJA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Int32" DbType="Int" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="FechaProcesado" Parameter="fechaProcesado" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_CUADRE_CAJAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCaja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaProcesado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_HISTORIAL_VENTA" Method="SP_GUARDAR_HISTORIAL_VENTA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EstatusFacturacion" Parameter="estatusFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusFActuracion" Parameter="idEstatusFActuracion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DescripciomComprobanre" Parameter="descripciomComprobanre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comprobante" Parameter="comprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdTipoVenta" Parameter="idTipoVenta" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoVenta" Parameter="tipoVenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CantidadDias" Parameter="cantidadDias" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCantidadDias" Parameter="idCantidadDias" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioVendio" Parameter="usuarioVendio" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaFActuracion" Parameter="fechaFActuracion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CantidadProductos" Parameter="cantidadProductos" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CantidadServicios" Parameter="cantidadServicios" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CantidadArticulos" Parameter="cantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TotalDescuento" Parameter="totalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="SubTotal" Parameter="subTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoImpuesto" Parameter="porcientoImpuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cambio" Parameter="cambio" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoPago" Parameter="tipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TotalGeneral" Parameter="totalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_HISTORIAL_VENTAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EstatusFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEstatusFActuracion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DescripciomComprobanre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdTipoVenta" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadDias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCantidadDias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioVendio" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaFActuracion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CantidadProductos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CantidadServicios" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_INFORMACION_GANANCIA" Method="SP_GUARDAR_INFORMACION_GANANCIA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusFacturacion" Parameter="idEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdFActura" Parameter="idFActura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="DescripcionProducto" Parameter="descripcionProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Acumulativo" Parameter="acumulativo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoProducto" Parameter="tipoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CantidadVendda" Parameter="cantidadVendda" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescuentoAplicado" Parameter="descuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalVenta" Parameter="totalVenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalPrecioCompra" Parameter="totalPrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Ganancia" Parameter="ganancia" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_INFORMACION_GANANCIAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdFActura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Acumulativo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadVendda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalPrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Ganancia" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MODIFICAR_INFORMACION_EMPRESA" Method="SP_MODIFICAR_INFORMACION_EMPRESA">
    <Parameter Name="IdInformacionEMpres" Parameter="idInformacionEMpres" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombreEmpresa" Parameter="nombreEmpresa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email2" Parameter="email2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Facebook" Parameter="facebook" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Instagram" Parameter="instagram" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="IdLogoEmpresa" Parameter="idLogoEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_INFORMACION_EMPRESAResult">
      <Column Name="IdInformacionEMpres" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagram" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdLogoEmpresa" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_SACAR_RUTA_BACKUP_BD" Method="SP_SACAR_RUTA_BACKUP_BD">
    <Parameter Name="IdRutaBackupBD" Parameter="idRutaBackupBD" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_SACAR_RUTA_BACKUP_BDResult">
      <Column Name="IdRutaBAckupBD" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Ruta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MODIFICAR_RUTA_BACKUP" Method="SP_MODIFICAR_RUTA_BACKUP">
    <Parameter Name="IdRutaBackup" Parameter="idRutaBackup" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Ruta" Parameter="ruta" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_RUTA_BACKUPResult">
      <Column Name="IdRutaBackup" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Ruta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_GENERAR_BACKUP_DATABASE" Method="SP_GENERAR_BACKUP_DATABASE">
    <Parameter Name="RutaBaseDatos" Parameter="rutaBaseDatos" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GENERAR_BACKUP_DATABASEResult">
      <Column Name="RutaArchivo" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MODIFICAR_IMPUESTO_VENTA" Method="SP_MODIFICAR_IMPUESTO_VENTA">
    <Parameter Name="IdImpuesto" Parameter="idImpuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PorcientoImpuesto" Parameter="porcientoImpuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Operacion" Parameter="operacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_IMPUESTO_VENTAResult">
      <Column Name="IdImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PorcientoImpuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Operacion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCA_TIPO_MAIL" Method="SP_BUSCA_TIPO_MAIL">
    <Parameter Name="IdTipoMail" Parameter="idTipoMail" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_MAILResult">
      <Column Name="IdTipoMail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoMail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="smtp" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Puerto" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCA_MAIL" Method="SP_BUSCA_MAIL">
    <Parameter Name="IdMail" Parameter="idMail" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_MAILResult">
      <Column Name="IdMail" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoCorreo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoMail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoMail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Puerto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="smtp" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MANTENIMIENTO_MAIL" Method="SP_MANTENIMIENTO_MAIL">
    <Parameter Name="IdMail" Parameter="idMail" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Mail" Parameter="mail" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdTipoCorreo" Parameter="idTipoCorreo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_MAILResult">
      <Column Name="IdMail" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoCorreo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_DATOS_REPORTE_PRODUCTOS_DEFECTUOSOS" Method="SP_GUARDAR_DATOS_REPORTE_PRODUCTOS_DEFECTUOSOS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Producto" Parameter="producto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoProducto" Parameter="tipoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="UnidadMedida" Parameter="unidadMedida" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Idmarca" Parameter="idmarca" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Marca" Parameter="marca" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdModelo" Parameter="idModelo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Modelo" Parameter="modelo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoSuplidor" Parameter="tipoSuplidor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdSuplidor" Parameter="idSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Suplidor" Parameter="suplidor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoBarra" Parameter="codigoBarra" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Referencia" Parameter="referencia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="StockMinimo" Parameter="stockMinimo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="PorcientoDescuento" Parameter="porcientoDescuento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="AfctaOferta0" Parameter="afctaOferta0" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AfectaOferta" Parameter="afectaOferta" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ProductoAcumulativo0" Parameter="productoAcumulativo0" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ProductoAcumulativo" Parameter="productoAcumulativo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="LlevaImagen0" Parameter="llevaImagen0" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LlevaImagen" Parameter="llevaImagen" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaAdiciona" Parameter="fechaAdiciona" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaCreado" Parameter="fechaCreado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UsuarioModifica" Parameter="usuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ModificadoPor" Parameter="modificadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaModifica" Parameter="fechaModifica" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaModificado" Parameter="fechaModificado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AplicaParaImpuesto0" Parameter="aplicaParaImpuesto0" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EstatusProducto0" Parameter="estatusProducto0" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EstatusProducto" Parameter="estatusProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AplicaImpuesto" Parameter="aplicaImpuesto" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CantidadAgregada" Parameter="cantidadAgregada" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ProductoConOferta" Parameter="productoConOferta" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ProductoProximoAgotarse" Parameter="productoProximoAgotarse" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ProductosAgostados" Parameter="productosAgostados" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TotalProductos" Parameter="totalProductos" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_REPORTE_PRODUCTOS_DEFECTUOSOSResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Idmarca" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdModelo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoSuplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Suplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoBarra" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Referencia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="AfctaOferta0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AfectaOferta" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductoAcumulativo0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductoAcumulativo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LlevaImagen0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LlevaImagen" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AplicaParaImpuesto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EstatusProducto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EstatusProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AplicaImpuesto" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CantidadAgregada" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ProductoConOferta" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ProductoProximoAgotarse" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ProductosAgostados" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalProductos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_BUSCAR_RUTA_ARCHIVO_TXT" Method="SP_BUSCAR_RUTA_ARCHIVO_TXT">
    <Parameter Name="IdRutaArchivostxt" Parameter="idRutaArchivostxt" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCAR_RUTA_ARCHIVO_TXTResult">
      <Column Name="IdRutaArchivotxt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ruta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MODIFICAR_RUTA_ARCHIVO_TXT" Method="SP_MODIFICAR_RUTA_ARCHIVO_TXT">
    <Parameter Name="IdRutaArchivotxt" Parameter="idRutaArchivotxt" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ruta" Parameter="ruta" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_RUTA_ARCHIVO_TXTResult">
      <Column Name="IdRutaArchivotxt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ruta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_DATOS_REPORTE_606" Method="SP_GUARDAR_DATOS_REPORTE_606">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCompraSuplidor" Parameter="idCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoSuplidor" Parameter="idTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoSuplidor" Parameter="tipoSuplidor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdSuplidor" Parameter="idSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Suplidor" Parameter="suplidor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNCCedula" Parameter="rNCCedula" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoBienesServicios" Parameter="idTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoBienesServicios" Parameter="tipoBienesServicios" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoTipoBienesServicio" Parameter="codigoTipoBienesServicio" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NCF" Parameter="nCF" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NCFMODIFICADO" Parameter="nCFMODIFICADO" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaComprobante0" Parameter="fechaComprobante0" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaComprobante" Parameter="fechaComprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaPago0" Parameter="fechaPago0" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaPago" Parameter="fechaPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoFacturadoServicios" Parameter="montoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoFacturadoBienes" Parameter="montoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalMontoFacturado" Parameter="totalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISFacturado" Parameter="iTBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISRetenido" Parameter="iTBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISSujetoProporcionalidad" Parameter="iTBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISLlevadoCosto" Parameter="iTBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPorAdelantar" Parameter="iTBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPercibidoCompras" Parameter="iTBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoRetencionISR" Parameter="idTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoRetencionISR" Parameter="tipoRetencionISR" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoTipoRetencionISR" Parameter="codigoTipoRetencionISR" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="MontoRetencionRenta" Parameter="montoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ISRPercibidoCompras" Parameter="iSRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoSelectivoConsumo" Parameter="impuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OtrosImpuestosTasa" Parameter="otrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPropinaLegal" Parameter="montoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdFormaPago" Parameter="idFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FormaPago" Parameter="formaPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoTipoPago" Parameter="codigoTipoPago" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaCreado0" Parameter="fechaCreado0" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCreado" Parameter="fechaCreado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ValidadoDesde" Parameter="validadoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ValidadoHasta" Parameter="validadoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_REPORTE_606Result">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCompraSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoSuplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdSuplidor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Suplidor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNCCedula" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoBienesServicios" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoBienesServicios" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoBienesServicio" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NCFMODIFICADO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaComprobante0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaPago0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoFacturadoServicios" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturadoBienes" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalMontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISSujetoProporcionalidad" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISLlevadoCosto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPorAdelantar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoRetencionISR" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoRetencionISR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoRetencionISR" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="MontoRetencionRenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ISRPercibidoCompras" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoSelectivoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosImpuestosTasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdFormaPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FormaPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaCreado0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_MODIFICAR_CONFIGURACION_GENERAL" Method="SP_MODIFICAR_CONFIGURACION_GENERAL">
    <Parameter Name="IdConfiguracionGeneral" Parameter="idConfiguracionGeneral" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_CONFIGURACION_GENERALResult">
      <Column Name="IdConfiguracionGeneral" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Configuracion.SP_OBTENER_PRIMER_DIA_MES" Method="SP_OBTENER_PRIMER_DIA_MES">
    <ElementType Name="SP_OBTENER_PRIMER_DIA_MESResult">
      <Column Name="PrimerDia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GENERAR_ARCHIVO_REPORTE_607" Method="SP_GENERAR_ARCHIVO_REPORTE_607">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHAsta" Parameter="fechaHAsta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_GENERAR_ARCHIVO_REPORTE_607Result">
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NCFModificado" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoIngreso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoIngreso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoIngreso" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaArchivo" Type="System.String" DbType="VarChar(92) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRetencion" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="MontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenidoPorTerceros" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ITBISPercibido" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RetencionRentaPorTerceros" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ISRPercibido" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ImpuestoSostenidoConsumo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="OtrosImpuestoTasa" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="MontoPropinaLegal" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="MontoEfectivo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoChequeTransferenciaDeposito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoTarjetaDebitoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoVentaCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="BonosCertificadosRegalos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Permuta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrasFormasVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_PROCESAR_INFORMACION_REPORTE_607" Method="SP_PROCESAR_INFORMACION_REPORTE_607">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NCF" Parameter="nCF" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NCFModificado" Parameter="nCFModificado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIngreso" Parameter="idTipoIngreso" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoIngreso" Parameter="tipoIngreso" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoTipoIngreso" Parameter="codigoTipoIngreso" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FechaFacturacion" Parameter="fechaFacturacion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaArchivo" Parameter="fechaArchivo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaRetencion" Parameter="fechaRetencion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MontoFacturado" Parameter="montoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoFacturado" Parameter="impuestoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISRetenidoPorTerceros" Parameter="iTBISRetenidoPorTerceros" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ITBISPercibido" Parameter="iTBISPercibido" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="RetencionRentaPorTerceros" Parameter="retencionRentaPorTerceros" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ISRPercibido" Parameter="iSRPercibido" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ImpuestoSostenidoConsumo" Parameter="impuestoSostenidoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OtrosImpuestoTasa" Parameter="otrosImpuestoTasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPropinaLegal" Parameter="montoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoEfectivo" Parameter="montoEfectivo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoChequeTransferenciaDeposito" Parameter="montoChequeTransferenciaDeposito" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoTarjetaDebitoCredito" Parameter="montoTarjetaDebitoCredito" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoVentaCredito" Parameter="montoVentaCredito" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="BonosCertificadosRegalos" Parameter="bonosCertificadosRegalos" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Permuta" Parameter="permuta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OtrasFormasVenta" Parameter="otrasFormasVenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_REPORTE_607Result">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NCF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NCFModificado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIngreso" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIngreso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoIngreso" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaArchivo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaRetencion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MontoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoFacturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISRetenidoPorTerceros" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ITBISPercibido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="RetencionRentaPorTerceros" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ISRPercibido" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ImpuestoSostenidoConsumo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrosImpuestoTasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPropinaLegal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoEfectivo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoChequeTransferenciaDeposito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoTarjetaDebitoCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoVentaCredito" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="BonosCertificadosRegalos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Permuta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OtrasFormasVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GENERAR_ARCHIVO_608" Method="SP_GENERAR_ARCHIVO_608">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_GENERAR_ARCHIVO_608Result">
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaFacturacion0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaArchivo" Type="System.String" DbType="VarChar(74) NOT NULL" CanBeNull="false" />
      <Column Name="TipoAnulacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoAnulacion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_PROCESAR_INFORMACION_REPORTE_608" Method="SP_PROCESAR_INFORMACION_REPORTE_608">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Comprobante" Parameter="comprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaFacturacion0" Parameter="fechaFacturacion0" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFActuracion" Parameter="fechaFActuracion" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="FechaArchivo" Parameter="fechaArchivo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="TipoAnulacion" Parameter="tipoAnulacion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="CodigoTipoAnulacion" Parameter="codigoTipoAnulacion" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ValidadoDesde" Parameter="validadoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ValidadoHasta" Parameter="validadoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_REPORTE_608Result">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaFacturacion0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFActuracion" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FechaArchivo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TipoAnulacion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CodigoTipoAnulacion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_PROCESAR_DATOS_REPORTES_FINANCIEROS" Method="SP_PROCESAR_DATOS_REPORTES_FINANCIEROS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="IdTipoCuenta" Parameter="idTipoCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoCuenta" Parameter="tipoCuenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdModulo" Parameter="idModulo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Modulo" Parameter="modulo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Conector" Parameter="conector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="Banco" Parameter="banco" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreBanco" Parameter="nombreBanco" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cuenta" Parameter="cuenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Valor" Parameter="valor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdOrigenCuenta" Parameter="idOrigenCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrigenCuenta" Parameter="origenCuenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CuentaConcepto" Parameter="cuentaConcepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="NumeroRelacionado" Parameter="numeroRelacionado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdClaseCuenta" Parameter="idClaseCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClaseCuenta" Parameter="claseCuenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCuentaContable" Parameter="idCuentaContable" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cuentadescargo" Parameter="cuentadescargo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_DATOS_REPORTES_FINANCIEROSResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IdTipoCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoCuenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdModulo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Modulo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Conector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Banco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreBanco" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdOrigenCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrigenCuenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CuentaConcepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="NumeroRelacionado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdClaseCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaseCuenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCuentaContable" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cuentadescargo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>